"""Regenerate the figures in README.md and HANDBOOK.md from the repository.

    python tools/readme_stats.py            rewrite them
    python tools/readme_stats.py --check    fail if they have drifted

The front page said 181 functions and 10,280 bytes when the truth was 1,200
and 34,096 -- wrong by a factor of six, in the first block a visitor reads,
and stale in five other places besides. It had been hand-maintained, which
is the same drift that let MATCHED.md's table and verify.py's match list
fall out of step with build.py. MATCHED.md's table is generated for exactly
this reason; the README's numbers were not, and so they rotted.

Every figure here is read from the artefacts that define it: the manifest,
the inventory, the candidate list, the attempts list. `--check` runs in
verify.py, so a stale README is a failing check rather than something a
reader discovers.

The counts are kept SPLIT -- hand-written against generated -- everywhere
they appear. A single total of 1,200 is true and misleading in the same
breath, because 818 of those are one-expression stubs a script wrote from
their own encodings.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from peimage import Image, load_inventory

ROOT = Path(__file__).resolve().parent.parent
# TWO documents carry these figures and both must be maintained.
#
# HANDBOOK.md is the working document -- the full generated block. README.md
# is the GitHub front page and carries only the headline line, because a
# front page that repeats every figure is a front page that goes stale in
# more places. Both are checked; a number that appears twice and is
# regenerated once is worse than a number that appears once.
DOC = ROOT / "HANDBOOK.md"
FRONT = ROOT / "README.md"
# Anchored to the whole LINE, not to a sentence. `[^.]*\.` stopped at the
# first full stop, which in this sentence is the one inside `.text` -- so it
# replaced two thirds of the line and left the tail behind, duplicated. A
# sentence-terminator is not a safe delimiter in text that contains file
# extensions, version numbers and percentages.
FRONT_RE = re.compile(r"^\*\*[\d,]+ functions matched\*\*.*$", re.M)
from category import category as _category                   # noqa: E402

BEGIN = "<!-- STATS: generated by tools/readme_stats.py -->"
END = "<!-- /STATS -->"


def rows(path):
    out = []
    p = ROOT / path
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = line.split()
        if len(f) >= 2:
            try:
                out.append((f[0], int(f[1], 16)))
            except ValueError:
                pass
    return out


def compiled_total(matched):
    """Bytes as build.py counts them -- the compiled length, not the extent."""
    import matched_table
    tot = {"hand": 0, "gen": 0, "up": 0}
    for src, addr in matched:
        sym = flags = None
        for line in (ROOT / "src/manifest.txt").read_text().splitlines():
            f = line.split()
            if len(f) >= 2 and f[0] == src:
                try:
                    if int(f[1], 16) != addr:
                        continue
                except ValueError:
                    continue
                for extra in f[2:]:
                    if extra.startswith("flags="):
                        flags = extra[len("flags="):]
                    elif extra != "-":
                        sym = extra
                break
        n = matched_table.compiled_size(src, sym, flags, addr)
        if n is None:
            continue
        tot[{"generated": "gen", "upstream": "up"}.get(
            _category(src), "hand")] += n
    return tot


def collect():
    img = Image()
    inv = load_inventory()
    text = next(s for s in img.sections if s["name"] == ".text")
    tsize = text["vsize"] or text["rawsz"]

    matched = rows("src/manifest.txt")
    attempts = rows("src/attempts.txt")
    hand = [r for r in matched if _category(r[0]) == "handwritten"]
    gen = [r for r in matched if _category(r[0]) == "generated"]
    up = [r for r in matched if _category(r[0]) == "upstream"]

    cand = 0
    cp = ROOT / "build/candidates.txt"
    if cp.exists():
        cand = sum(1 for l in cp.read_text().splitlines()
                   if l.strip() and not l.startswith("#"))

    b = compiled_total(matched)
    built = b["hand"] + b["gen"] + b["up"]
    return {
        "inv": len(inv),
        "text": tsize,
        "matched": len(matched),
        "hand": len(hand),
        "gen": len(gen),
        "up": len(up),
        "hand_bytes": b["hand"],
        "gen_bytes": b["gen"],
        "up_bytes": b["up"],
        "built": built,
        "pct": 100.0 * built / tsize,
        "attempts": len(attempts),
        "cand": cand,
    }


def block(s):
    return (
        "%s\n```\n"
        "function starts known           %s\n"
        ".text                           %s bytes\n"
        "\n"
        "FUNCTIONS MATCHED               %s\n"
        "  read off the disassembly      %s   (%s bytes)\n"
        "  generated from encodings      %s   (%s bytes)\n"
        "  upstream third-party source   %s   (%s bytes)\n"
        "\n"
        "bytes rebuilt from source       %s   (%.4f%% of .text)\n"
        "near-misses recorded            %s\n"
        "vetted match candidates         %s\n"
        "```\n"
        "The three parts of the match count are never added up without\n"
        "being split, here or anywhere else. The generated ones are a\n"
        "single expression each, written by script from the instructions\n"
        "themselves. The upstream ones are libogg 1.1.3 and libvorbis\n"
        "1.2.0, obtained rather than recovered -- the release pair decided\n"
        "by measurement in FINDINGS 8a. Both reproduce the image exactly\n"
        "and a link needs every one; only the first says anything about how\n"
        "much of this game has been read.\n%s"
        % (BEGIN,
           "{:,}".format(s["inv"]), "{:,}".format(s["text"]),
           "{:,}".format(s["matched"]),
           "{:,}".format(s["hand"]), "{:,}".format(s["hand_bytes"]),
           "{:,}".format(s["gen"]), "{:,}".format(s["gen_bytes"]),
           "{:,}".format(s["up"]), "{:,}".format(s["up_bytes"]),
           "{:,}".format(s["built"]), s["pct"],
           "{:,}".format(s["attempts"]), "{:,}".format(s["cand"]),
           END))


def main(argv):
    s = collect()
    doc = DOC.read_text(encoding="utf-8")

    if BEGIN in doc and END in doc:
        i = doc.index(BEGIN)
        j = doc.index(END) + len(END)
        new = doc[:i] + block(s) + doc[j:]
    else:
        # First run: replace the hand-written block that starts the file's
        # status section, identified by its own first line.
        m = re.search(r"```\nfunctions known[^`]*```", doc)
        if not m:
            print("Cannot find the stats block to replace, and no markers")
            print("are present. Add the markers by hand once:")
            print("    %s ... %s" % (BEGIN, END))
            return 1
        new = doc[:m.start()] + block(s) + doc[m.end():]

    # The figures that recur in prose. Anchored tightly: a loose pattern
    # here would rewrite sentences it does not understand.
    new = re.sub(r"Only [\d,]+ of [\d,]+ `\.text` bytes\n\([\d.]+%\) are actually built",
                 "Only %s of %s `.text` bytes\n(%.4f%%) are actually built"
                 % ("{:,}".format(s["built"]), "{:,}".format(s["text"]),
                    s["pct"]),
                 new)

    # The front page's one headline sentence.
    front = FRONT.read_text(encoding="utf-8") if FRONT.exists() else None
    front_new = front
    if front is not None:
        line = ("**%s functions matched** — %s written by hand from the "
                "disassembly, %s generated from their own encodings, %s "
                "upstream libogg/libvorbis — reproducing %s of the %s bytes "
                "in `.text`, %.4f%%."
                % ("{:,}".format(s["matched"]), "{:,}".format(s["hand"]),
                   "{:,}".format(s["gen"]), "{:,}".format(s["up"]),
                   "{:,}".format(s["built"]), "{:,}".format(s["text"]),
                   s["pct"]))
        if FRONT_RE.search(front):
            front_new = FRONT_RE.sub(lambda _m: line, front, count=1)

    if "--check" in argv:
        same = (new == doc) and (front_new == front)
        which = []
        if new != doc:
            which.append("HANDBOOK.md")
        if front_new != front:
            which.append("README.md")
        print("figures are %s (%d matched, %s bytes)%s"
              % ("up to date" if same else "STALE -- run without --check",
                 s["matched"], "{:,}".format(s["built"]),
                 ("  stale: " + ", ".join(which)) if which else ""))
        return 0 if same else 1

    DOC.write_text(new, encoding="utf-8")
    if front_new is not None and front_new != front:
        FRONT.write_text(front_new, encoding="utf-8")
    print("HANDBOOK.md + README.md: %d matched (%d hand-written, %d "
          "generated), %s bytes, %.4f%%"
          % (s["matched"], s["hand"], s["gen"],
             "{:,}".format(s["built"]), s["pct"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
