"""Regenerate the figures in README.md from the repository itself.

    python tools/readme_stats.py            rewrite them
    python tools/readme_stats.py --check    fail if they have drifted

The front page said 181 functions and 10,280 bytes when the truth was 1,200
and 34,096 -- wrong by a factor of six, in the first block a visitor reads,
and stale in five other places besides. It had been hand-maintained, which
is the same drift that let MATCHED.md's table and verify.py's match list
fall out of step with build.py. MATCHED.md's table is generated for exactly
this reason; the README's numbers were not, and so they rotted.

Every figure here is read from the artefacts that define it: the manifest,
the inventory, the candidate list, the attempts list. `--check` runs in
verify.py, so a stale README is a failing check rather than something a
reader discovers.

The counts are kept SPLIT -- hand-written against generated -- everywhere
they appear. A single total of 1,200 is true and misleading in the same
breath, because 818 of those are one-expression stubs a script wrote from
their own encodings.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from peimage import Image, load_inventory

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "README.md"
GENERATED = ("vt_typeid_", "vt_const_", "vt_acc_")

BEGIN = "<!-- STATS: generated by tools/readme_stats.py -->"
END = "<!-- /STATS -->"


def rows(path):
    out = []
    p = ROOT / path
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = line.split()
        if len(f) >= 2:
            try:
                out.append((f[0], int(f[1], 16)))
            except ValueError:
                pass
    return out


def compiled_total(matched):
    """Bytes as build.py counts them -- the compiled length, not the extent."""
    import matched_table
    tot = {"hand": 0, "gen": 0}
    for src, addr in matched:
        sym = flags = None
        for line in (ROOT / "src/manifest.txt").read_text().splitlines():
            f = line.split()
            if len(f) >= 2 and f[0] == src:
                try:
                    if int(f[1], 16) != addr:
                        continue
                except ValueError:
                    continue
                for extra in f[2:]:
                    if extra.startswith("flags="):
                        flags = extra[len("flags="):]
                    elif extra != "-":
                        sym = extra
                break
        n = matched_table.compiled_size(src, sym, flags, addr)
        if n is None:
            continue
        tot["gen" if Path(src).name.startswith(GENERATED) else "hand"] += n
    return tot


def collect():
    img = Image()
    inv = load_inventory()
    text = next(s for s in img.sections if s["name"] == ".text")
    tsize = text["vsize"] or text["rawsz"]

    matched = rows("src/manifest.txt")
    attempts = rows("src/attempts.txt")
    hand = [r for r in matched if not Path(r[0]).name.startswith(GENERATED)]
    gen = [r for r in matched if Path(r[0]).name.startswith(GENERATED)]

    cand = 0
    cp = ROOT / "build/candidates.txt"
    if cp.exists():
        cand = sum(1 for l in cp.read_text().splitlines()
                   if l.strip() and not l.startswith("#"))

    b = compiled_total(matched)
    built = b["hand"] + b["gen"]
    return {
        "inv": len(inv),
        "text": tsize,
        "matched": len(matched),
        "hand": len(hand),
        "gen": len(gen),
        "hand_bytes": b["hand"],
        "gen_bytes": b["gen"],
        "built": built,
        "pct": 100.0 * built / tsize,
        "attempts": len(attempts),
        "cand": cand,
    }


def block(s):
    return (
        "%s\n```\n"
        "function starts known           %s\n"
        ".text                           %s bytes\n"
        "\n"
        "FUNCTIONS MATCHED               %s\n"
        "  read off the disassembly      %s   (%s bytes)\n"
        "  generated from encodings      %s   (%s bytes)\n"
        "\n"
        "bytes rebuilt from source       %s   (%.4f%% of .text)\n"
        "near-misses recorded            %s\n"
        "vetted match candidates         %s\n"
        "```\n"
        "The two halves of the match count are never added up without being\n"
        "split, here or anywhere else: the generated ones are a single\n"
        "expression each, written by script from the instructions\n"
        "themselves. They are real matches and a link needs them; they say\n"
        "much less than the hand-written ones about how much of this game\n"
        "has been read.\n%s"
        % (BEGIN,
           "{:,}".format(s["inv"]), "{:,}".format(s["text"]),
           "{:,}".format(s["matched"]),
           "{:,}".format(s["hand"]), "{:,}".format(s["hand_bytes"]),
           "{:,}".format(s["gen"]), "{:,}".format(s["gen_bytes"]),
           "{:,}".format(s["built"]), s["pct"],
           "{:,}".format(s["attempts"]), "{:,}".format(s["cand"]),
           END))


def main(argv):
    s = collect()
    doc = DOC.read_text(encoding="utf-8")

    if BEGIN in doc and END in doc:
        i = doc.index(BEGIN)
        j = doc.index(END) + len(END)
        new = doc[:i] + block(s) + doc[j:]
    else:
        # First run: replace the hand-written block that starts the file's
        # status section, identified by its own first line.
        m = re.search(r"```\nfunctions known[^`]*```", doc)
        if not m:
            print("Cannot find the stats block to replace, and no markers")
            print("are present. Add the markers by hand once:")
            print("    %s ... %s" % (BEGIN, END))
            return 1
        new = doc[:m.start()] + block(s) + doc[m.end():]

    # The figures that recur in prose. Anchored tightly: a loose pattern
    # here would rewrite sentences it does not understand.
    new = re.sub(r"Only [\d,]+ of [\d,]+ `\.text` bytes\n\([\d.]+%\) are actually built",
                 "Only %s of %s `.text` bytes\n(%.4f%%) are actually built"
                 % ("{:,}".format(s["built"]), "{:,}".format(s["text"]),
                    s["pct"]),
                 new)

    if "--check" in argv:
        same = (new == doc)
        print("README figures are %s (%d matched, %s bytes)"
              % ("up to date" if same else "STALE -- run without --check",
                 s["matched"], "{:,}".format(s["built"])))
        return 0 if same else 1

    DOC.write_text(new, encoding="utf-8")
    print("README: %d matched (%d hand-written, %d generated), %s bytes, "
          "%.4f%%" % (s["matched"], s["hand"], s["gen"],
                      "{:,}".format(s["built"]), s["pct"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
