#include "types.h"

// Single-expression accessors, 26 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_82755A40(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 20));
    float t1 = (*(float*)((char*)a1 + 24));
    float t2 = (*(float*)((char*)a1 + 28));
    float t3 = (*(float*)((char*)a1 + 32));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_82772DA0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(a1 + 0x10u);
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(a1 + 0x10u);
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
}
void Acc_8277A8B0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 116) = (unsigned char)((*(unsigned char*)((char*)a0 + 116)) | 0x1u);
}
void Acc_82782790(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 4));
    float t1 = (*(float*)((char*)a1 + 8));
    float t2 = (*(float*)((char*)a1 + 12));
    float t3 = (*(float*)((char*)a1 + 16));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_827830B8(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 64));
    float t1 = (*(float*)((char*)a1 + 68));
    float t2 = (*(float*)((char*)a1 + 72));
    float t3 = (*(float*)((char*)a1 + 76));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_827830E0(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 12));
    float t1 = (*(float*)((char*)a1 + 8));
    float t2 = (*(float*)((char*)a1 + 4));
    float t3 = (*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 64) = (float)t3;
    *(float*)((char*)a0 + 68) = (float)t2;
    *(float*)((char*)a0 + 72) = (float)t1;
    *(float*)((char*)a0 + 76) = (float)t0;
}
void Acc_82787540(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 108));
    float t1 = (*(float*)((char*)a1 + 112));
    float t2 = (*(float*)((char*)a1 + 116));
    float t3 = (*(float*)((char*)a1 + 120));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_82787568(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 12));
    float t1 = (*(float*)((char*)a1 + 8));
    float t2 = (*(float*)((char*)a1 + 4));
    float t3 = (*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 108) = (float)t3;
    *(float*)((char*)a0 + 112) = (float)t2;
    *(float*)((char*)a0 + 116) = (float)t1;
    *(float*)((char*)a0 + 120) = (float)t0;
}
void Acc_82789000(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)a1 + 20));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a1 + 24));
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 28));
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 32));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned int*)((char*)a1 + 36));
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)(*(unsigned int*)((char*)a1 + 40));
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)(*(unsigned int*)((char*)a1 + 44));
    *(unsigned char*)((char*)a0 + 36) = (unsigned char)(*(unsigned char*)((char*)a1 + 48));
}
unsigned int Acc_827AB828(char* a0, char* a1, unsigned int a2, unsigned int a3)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 0));
    unsigned int t1 = (*(unsigned int*)((char*)a0 + 84));
    unsigned int t2 = (*(unsigned int*)((char*)a0 + 80));
    unsigned int t3 = (*(unsigned int*)((char*)a0 + 72));
    *(unsigned char*)((char*)t0 + 3) = (unsigned char)0x1u;
    *(unsigned short*)((char*)t0 + 6) = (unsigned short)t1;
    *(unsigned short*)((char*)t0 + 4) = (unsigned short)t2;
    *(unsigned int*)((char*)t0 + 8) = (unsigned int)a2;
    *(unsigned int*)((char*)t0 + 12) = (unsigned int)t3;
    *(unsigned char*)((char*)t0 + 1) = (unsigned char)a3;
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(t0 + 0x10u);
    return (unsigned int)t3;
}
void Acc_827DA410(char* a0)
{
    *(unsigned int*)((char*)a0 + 1) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 4));
}
void Acc_827E9F00(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 220));
    float t1 = (*(float*)((char*)a1 + 224));
    float t2 = (*(float*)((char*)a1 + 228));
    float t3 = (*(float*)((char*)a1 + 232));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_827E9F28(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 12));
    float t1 = (*(float*)((char*)a1 + 8));
    float t2 = (*(float*)((char*)a1 + 4));
    float t3 = (*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 220) = (float)t3;
    *(float*)((char*)a0 + 224) = (float)t2;
    *(float*)((char*)a0 + 228) = (float)t1;
    *(float*)((char*)a0 + 232) = (float)t0;
}
void Acc_827F8708(char* a0, char* a1)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 28)) << 0x3u) + (*(unsigned int*)((char*)a0 + 32))) + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 28)) << 0x3u) + (*(unsigned int*)((char*)a0 + 32))) + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
}
void Acc_827F8730(char* a0, char* a1, unsigned int a2)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 32));
    unsigned int t1 = (*(unsigned int*)((char*)(t0 + (a2 << 0x3u)) + 0));
    unsigned int t2 = (*(unsigned int*)((char*)(t0 + (a2 << 0x3u)) + 4));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t2;
}
void Acc_828493D0(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 16));
    float t1 = (*(float*)((char*)a1 + 20));
    float t2 = (*(float*)((char*)a1 + 24));
    float t3 = (*(float*)((char*)a1 + 28));
    *(float*)((char*)a0 + 0) = (float)t0;
    *(float*)((char*)a0 + 4) = (float)t1;
    *(float*)((char*)a0 + 8) = (float)t2;
    *(float*)((char*)a0 + 12) = (float)t3;
}
void Acc_8286C930(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x5u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 48));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 12) = (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 12)) + 0x1u);
}
void Acc_8286F7A8(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x2u;
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)(*(unsigned char*)((char*)a1 + 48));
}
void Acc_8288E5E8(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)a2;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a3;
}
void Acc_82890F60(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x400u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x400u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 64) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 72) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 88) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 92) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 96) = (unsigned int)0x0u;
}
unsigned int Acc_82897A38(void)
{
    return (unsigned int)(0x0u & 0xFFu);
}
unsigned int Acc_828B3E2C(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
void Acc_828CF278(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((a0 + 0x14u) + 0x8u);
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)((*(unsigned int*)((char*)a0 + 24)) + 0x4u) + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 20));
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)((*(unsigned int*)((char*)a0 + 24)) + 0x4u);
}
unsigned int Acc_828DBF78(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 100));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 104));
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 108));
    *(unsigned int*)((char*)a1 + 16) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 112));
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 48));
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 88));
    return (unsigned int)0x0u;
}
unsigned int Acc_828DC620(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 124)) + 100));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 124)) + 104));
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 124)) + 108));
    *(unsigned int*)((char*)a1 + 16) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 124)) + 112));
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 124)) + 88));
    return (unsigned int)0x0u;
}
unsigned int Acc_828DDED8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x2u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 100));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 104));
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 108));
    *(unsigned int*)((char*)a1 + 16) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 112));
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 48));
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)0x1u;
    return (unsigned int)0x0u;
}
