#include "types.h"

// Single-expression accessors, 2 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

u32 Acc_828DE488(void* p) { return *(u32*)((char*)p + 36); }
void Acc_828F9218(void* p, u32 v) { *(u32*)((char*)p + 264) = v; }
