#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_821FE658(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_821FE6C0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned char*)((char*)a1 + 4));
    *(unsigned char*)((char*)a0 + 28) = (unsigned char)(*(unsigned char*)((char*)a1 + 5));
}
void Acc_821FE6E0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned char*)((char*)a1 + 0)) + 0xFFFFFFFFu);
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned char*)((char*)a1 + 1));
}
void Acc_821FE6F8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)((*(unsigned char*)((char*)a1 + 0)) + 0xFFFFFFFFu);
}
void Acc_821FE730(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned char*)((char*)a1 + 4)) + 0xFFFFFFFFu);
}
void Acc_82201090(int unused0, char* a1, char* a2)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 60));
    *(float*)((char*)a1 + 4) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 64));
    *(float*)((char*)a1 + 8) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 68));
}
unsigned int Acc_82201638(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 60));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 64));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 68));
    return (unsigned int)0x1u;
}
void Acc_82201818(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a3;
}
unsigned int Acc_822020A0(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 8));
}
void Acc_82202D68(char* a0)
{
    *(unsigned char*)((char*)a0 + 125) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 56) = (unsigned char)(*(unsigned char*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 196)) + 124)) + 0)) + 144));
}
void Acc_82202EF8(char* a0)
{
    *(unsigned char*)((char*)a0 + 56) = (unsigned char)(*(unsigned char*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 196)) + 124)) + 0)) + 144));
}
void Acc_82203788(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 24));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 28));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 32));
}
unsigned int Acc_822038A0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 0)) + 56)) >> 0x3u) & 0x1u);
}
void Acc_822073B0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 4));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 8));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 12));
}
void Acc_82218DC0(char* a0)
{
    *(unsigned char*)((char*)a0 + 171) = (unsigned char)0x1u;
}
void Acc_82218DD0(char* a0)
{
    *(unsigned char*)((char*)a0 + 171) = (unsigned char)0x0u;
}
unsigned int Acc_82219038(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(((a2 + (a2 << 0x1u)) << 0x2u) + (*(unsigned int*)((char*)a0 + 0)));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
unsigned int Acc_82219058(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)((a2 << 0x2u) + (*(unsigned int*)((char*)a0 + 0)));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
void Acc_82219788(char* a0)
{
    *(unsigned char*)((char*)a0 + 77) = (unsigned char)0x1u;
}
void Acc_8221E070(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 128));
}
void Acc_8221E080(char* a0, float f0)
{
    *(float*)((char*)a0 + 80) = (float)f0;
}
void Acc_8221E088(char* a0, float f0)
{
    *(float*)((char*)a0 + 96) = (float)f0;
}
void Acc_8221E090(char* a0, float f0)
{
    *(float*)((char*)a0 + 100) = (float)f0;
}
void Acc_8221E098(char* a0, float f0)
{
    *(float*)((char*)a0 + 120) = (float)f0;
}
unsigned int Acc_822264C8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 92)) + 0x98u);
}
unsigned int Acc_82234F40(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 56)) + 0x30u);
}
void Acc_8224B758(char* a0, float f0)
{
    *(float*)((char*)a0 + 144) = (float)f0;
}
unsigned int Acc_8224BAA0(char* a0)
{
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_8224C9A0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 96)) == 0x9u);
}
unsigned int Acc_8224C9E0(char* a0)
{
    *(unsigned char*)((char*)a0 + 110) = (unsigned char)0x0u;
    return (unsigned int)0x1u;
}
unsigned int Acc_8224C9F8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 96)) == 0x5u);
}
void Acc_8224D2C8(char* a0, char* a1)
{
    *(float*)((char*)a0 + 356) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 360) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 364) = (float)(*(float*)((char*)a1 + 8));
}
void Acc_8224D2E8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 520) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 524) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 528) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(unsigned int*)((char*)a0 + 532) = (unsigned int)(*(unsigned int*)((char*)a1 + 12));
}
unsigned int Acc_8224D4C0(int unused0, char* a1)
{
    return (unsigned int)((*(unsigned int*)((char*)a1 + 32)) == 0x56u);
}
unsigned int Acc_8224EB90(char* a0)
{
    *(unsigned char*)((char*)a0 + 7) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 6) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 5) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)0x0u;
    return (unsigned int)(a0 + 0x4u);
}
void Acc_82250E18(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a2;
}
void Acc_82250E28(char* a0, float f0, float f1)
{
    *(float*)((char*)a0 + 24) = (float)f0;
    *(float*)((char*)a0 + 28) = (float)f1;
}
void Acc_82250E38(char* a0, float f0)
{
    *(float*)((char*)a0 + 32) = (float)f0;
}
unsigned int Acc_822528E8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 136)) + 20));
}
unsigned int Acc_82253680(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 244));
}
