#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82102600(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10568)) & 0x7u);
}
unsigned int Acc_82102630(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10568)) >> 0x3u) & 0xFFu);
}
unsigned int Acc_82102668(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10556)) >> 0x3u) & 0x1u);
}
unsigned int Acc_821026F8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 11860)) >> 0x1Fu);
}
unsigned int Acc_82102788(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11856)) >> 0x5u) & 0x7u);
}
unsigned int Acc_82102818(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 11856)) & 0x1Fu);
}
unsigned int Acc_821028A8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11856)) >> 0x8u) & 0x1Fu);
}
unsigned int Acc_82102918(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11856)) >> 0x15u) & 0x7u);
}
unsigned int Acc_82102988(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 11856)) & 0x1Fu);
}
unsigned int Acc_821029F8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 11856)) & 0x1Fu);
}
unsigned int Acc_82102A90(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11860)) >> 0x1Eu) & 0x1u);
}
unsigned int Acc_82102B28(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10556)) & 0x7u);
}
unsigned int Acc_82102C70(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10680)) >> 0xAu) & 0x1u);
}
unsigned int Acc_82102D18(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 23980)) & 0x1u);
}
unsigned int Acc_82102D88(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x2u) & 0x1u);
}
unsigned int Acc_82102DC0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x4u) & 0x7u);
}
unsigned int Acc_82102E38(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x7u) & 0x1u);
}
unsigned int Acc_82102E68(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x8u) & 0x7u);
}
unsigned int Acc_82102EA0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0xBu) & 0x7u);
}
unsigned int Acc_82102ED8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x11u) & 0x7u);
}
unsigned int Acc_82102F08(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0xEu) & 0x7u);
}
unsigned int Acc_82102F38(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x14u) & 0x7u);
}
unsigned int Acc_82102F70(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x17u) & 0x7u);
}
unsigned int Acc_82102FA8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10548)) >> 0x1Du);
}
unsigned int Acc_82102FD8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10548)) >> 0x1Au) & 0x7u);
}
unsigned int Acc_821030F0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10564)) & 0x3Fu);
}
unsigned int Acc_821032A8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10568)) >> 0xFu) & 0x1u);
}
unsigned int Acc_82103758(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10540)) & 0xFu);
}
unsigned int Acc_82103768(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10540)) >> 0x4u) & 0xFu);
}
unsigned int Acc_82103778(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10540)) >> 0x8u) & 0xFu);
}
unsigned int Acc_82103788(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10540)) >> 0xCu) & 0xFu);
}
unsigned int Acc_82103798(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 10540)) & 0xFu);
}
unsigned int Acc_821037A8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10540)) >> 0x14u) & 0xFu);
}
unsigned int Acc_821037B8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 10540)) & 0xFu);
}
unsigned int Acc_821037C8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10540)) >> 0x1Cu);
}
unsigned int Acc_821037D8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10544)) & 0xFu);
}
unsigned int Acc_821037E8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10544)) >> 0x4u) & 0xFu);
}
unsigned int Acc_821037F8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10544)) >> 0x8u) & 0xFu);
}
unsigned int Acc_82103808(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10544)) >> 0xCu) & 0xFu);
}
unsigned int Acc_82103818(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 10544)) & 0xFu);
}
