#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

void Acc_82157C00(void* p, u8 v) { *(u8*)((char*)p + 2084) = v; }
void Acc_8219E878() { }
float Acc_8219F298(void* p) { return *(float*)((char*)p + 2756); }
u8 Acc_821A24A8(void* p) { return *(u8*)((char*)p + 28); }
void* Acc_821A4618(void* p) { return (char*)p + 468; }
void* Acc_821A4620(void* p) { return (char*)p + 516; }
u32 Acc_821A4648(void* p) { return *(u32*)((char*)p + 16); }
void Acc_821A47D8(void* p, u32 v) { *(u32*)((char*)p + 4) = v; }
void Acc_821A4978(void* p, u32 v) { *(u32*)((char*)p + 16) = v; }
void* Acc_821A5158(void* p) { return (char*)p + 116; }
void* Acc_821A5180(void* p) { return (char*)p + 180; }
u8 Acc_821A5918(void* p) { return *(u8*)((char*)p + 80); }
void* Acc_821AA898(void* p) { return (char*)p + 356; }
void Acc_821AAA98(void* p, u32 v) { *(u32*)((char*)p + 1984) = v; }
float Acc_821AEBB8(void* p) { return *(float*)((char*)p + 416); }
float Acc_821AEBC0(void* p) { return *(float*)((char*)p + 432); }
float Acc_821AEBC8(void* p) { return *(float*)((char*)p + 424); }
void* Acc_821C2AF8(void* p) { return (char*)p + 368; }
float Acc_821C2B00(void* p) { return *(float*)((char*)p + 1040); }
void* Acc_821C6A18(void* p) { return (char*)p + 552; }
void Acc_821C7920(void* p, u32 v) { *(u32*)((char*)p + 12) = v; }
void* Acc_821C8990(void* p) { return (char*)p + 68; }
void* Acc_821C89D8(void* p) { return (char*)p + 80; }
float Acc_821C89E0(void* p) { return *(float*)((char*)p + 80); }
float Acc_821C89E8(void* p) { return *(float*)((char*)p + 84); }
float Acc_821C89F0(void* p) { return *(float*)((char*)p + 88); }
void* Acc_821D9A08(void* p) { return (char*)p + 24; }
void* Acc_821D9A30(void* p) { return (char*)p + 1340; }
void Acc_821F6B68(void* p, u8 v) { *(u8*)((char*)p + 130) = v; }
void Acc_821F6DE0(void* p, u8 v) { *(u8*)((char*)p + 110) = v; }
void Acc_821F94E8(void* p, u32 v) { *(u32*)((char*)p + 72) = v; }
void Acc_821F97C0(void* p, u32 v) { *(u32*)((char*)p + 8) = v; }
u32 Acc_821F9910(void* p) { return *(u32*)((char*)p + 0); }
void Acc_821FD140(void* p, u32 v) { *(u32*)((char*)p + 20) = v; }
u32 Acc_822015E0(void* p) { return *(u32*)((char*)p + 584); }
u32 Acc_82202208(void* p) { return *(u32*)((char*)p + 480); }
void Acc_82202658(void* p, u32 v) { *(u32*)((char*)p + 52) = v; }
u32 Acc_822158C0(void* p) { return *(u32*)((char*)p + 416); }
void* Acc_82216DA0(void* p) { return (char*)p + 3912; }
float Acc_82216DD8(void* p) { return *(float*)((char*)p + 5192); }
