#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_826CDD98(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
unsigned int Acc_826CF560(int unused0, unsigned int a1)
{
    return (unsigned int)a1;
}
void Acc_826D3968(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x8u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x48u;
}
void Acc_826D46B0(char* a0, float f0)
{
    *(float*)((char*)a0 + 216) = (float)f0;
}
void Acc_826D46C0(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 214) = (unsigned char)(0x1u << a1);
}
unsigned int Acc_826D46D0(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 214)) >> 0x1u);
}
void Acc_826D4748(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x8u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x50u;
}
void Acc_826D4F50(char* a0, float f0)
{
    *(float*)((char*)a0 + 68) = (float)f0;
}
void Acc_826D4F60(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 66) = (unsigned char)(0x1u << a1);
}
unsigned int Acc_826D4F70(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 66)) >> 0x1u);
}
void Acc_826D4FD8(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_826D7780(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
}
void Acc_826D7790(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)((*(unsigned int*)((char*)a1 + 0)) + (*(unsigned int*)((char*)a2 + 0)));
}
void Acc_826D7858(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)0x0u;
}
void Acc_826D7F5C(int unused0, char* a1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)a7;
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)a1;
}
unsigned int Acc_826D8E38(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 520)) - ((*(unsigned int*)((char*)a0 + 424)) << (*(unsigned int*)((char*)a0 + 20)))) - (*(unsigned int*)((char*)a0 + 524)));
}
void Acc_826DA328(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a1 + 12) = (unsigned char)0x1u;
}
unsigned int Acc_826DA378(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 72));
}
unsigned int Acc_826DA388(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 72)) - ((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 96)) << (*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 76))));
}
void Acc_826DD418(int unused0, char* a1, unsigned int a2)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 18) = (unsigned char)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 18)) | a2);
}
unsigned int Acc_826E3788(int unused0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    return (unsigned int)a7;
}
void Acc_826E6E08(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 212));
}
void Acc_826E6E18(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 212) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_826EC0C0(char* a0)
{
    *(unsigned char*)((char*)a0 + 16) = (unsigned char)0x1u;
}
void Acc_826ED1D0(char* a0, char* a1)
{
    *(float*)((char*)(*(unsigned int*)((char*)a1 + 8)) + 20) = (float)(*(float*)((char*)a0 + 8));
    *(float*)((char*)(*(unsigned int*)((char*)a1 + 8)) + 24) = (float)(*(float*)((char*)a0 + 8));
}
unsigned int Acc_826EED30(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 164)) + 0xFFFFFFFFu);
}
unsigned int Acc_826EED40(char* a0)
{
    return (unsigned int)(((((*(unsigned int*)((char*)a0 + 164)) - (*(unsigned int*)((char*)a0 + 208))) + (((*(unsigned int*)((char*)a0 + 164)) - (*(unsigned int*)((char*)a0 + 208))) << 0x1u)) << 0x3u) + 0x24u);
}
void Acc_826FCC30(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned short*)((char*)a0 + 30));
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)((*(unsigned short*)((char*)a0 + 28)) + 0x34u);
}
unsigned int Acc_826FD2E8(char* a0)
{
    return (unsigned int)(((*(unsigned char*)((char*)a0 + 23)) + 0x1u) + (((*(unsigned char*)((char*)a0 + 23)) + 0x1u) << 0x1u));
}
void Acc_826FFAC8(char* a0)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
}
void Acc_827007D0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 20));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 24));
}
void Acc_827008B8(char* a0)
{
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)0x1u;
}
void Acc_827008C8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
}
void Acc_82700980(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 20));
}
unsigned int Acc_82700CE8(char* a0)
{
    return (unsigned int)((a0 - (*(unsigned int*)((char*)a0 + 24))) + 0x4Cu);
}
unsigned int Acc_827046B0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 12)) & 0x1u);
}
unsigned int Acc_827046C0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 12)) >> 0x4u) & 0x1u);
}
unsigned int Acc_827046D0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 12)) >> 0x1u) & 0x1u);
}
unsigned int Acc_82707DF8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 52));
}
unsigned int Acc_82707E08(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 128));
}
