#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_8216B318(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)((*(unsigned int*)((char*)a0 + 32)) + a1);
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 40)));
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)((*(unsigned int*)((char*)a0 + 48)) + a1);
}
void Acc_8216B340(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)((*(unsigned int*)((char*)a0 + 16)) + a1);
}
void Acc_8216B350(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)((*(unsigned int*)((char*)a0 + 0)) + a1);
}
void Acc_8216B360(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)((*(unsigned int*)((char*)a0 + 12)) + a1);
}
void Acc_8216B378(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)((*(unsigned int*)((char*)a0 + 36)) + a1);
}
void Acc_8216B388(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 72) = (unsigned int)((*(unsigned int*)((char*)a0 + 72)) + a1);
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 76)));
}
void Acc_8216B3E8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)((*(unsigned int*)((char*)a0 + 40)) + a1);
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 44)));
}
void Acc_8216B470(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)((*(unsigned int*)((char*)a0 + 68)) + a1);
}
void Acc_8216B480(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + a1);
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 12)));
}
void Acc_8216B4F8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + a1);
}
void Acc_8216B508(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 272) = (unsigned int)((*(unsigned int*)((char*)a0 + 272)) + a1);
}
unsigned int Acc_8219B568(char* a0, int unused1, char* a2)
{
    *(float*)((char*)a2 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 20));
    return (unsigned int)0x1u;
}
void Acc_8219B580(char* a0, float f0)
{
    *(float*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 20) = (float)f0;
}
float Acc_8219B590(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 40));
}
void Acc_8219B5A0(char* a0, float f0)
{
    *(float*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 40) = (float)f0;
}
void Acc_8219E2C8(char* a0)
{
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)0x0u;
}
void Acc_8219E3D0(char* a0)
{
    *(unsigned int*)((char*)a0 + 452) = (unsigned int)(*(unsigned int*)((char*)a0 + 448));
    *(unsigned int*)((char*)a0 + 448) = (unsigned int)(*(unsigned int*)((char*)a0 + 452));
}
void Acc_8219E518(char* a0)
{
    *(unsigned int*)((char*)a0 + 1148) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 1116) = (unsigned int)0x0u;
}
void Acc_8219E528(char* a0)
{
    *(unsigned int*)((char*)a0 + 1152) = (unsigned int)0x0u;
}
unsigned int Acc_8219E538(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 1152)) == 0x2u);
}
void Acc_8219F608(char* a0)
{
    *(unsigned char*)((char*)a0 + 2268) = (unsigned char)0x1u;
}
void Acc_8219F6C0(char* a0)
{
    *(unsigned char*)((char*)a0 + 2336) = (unsigned char)0x1u;
}
unsigned int Acc_821A09E0(char* a0)
{
    return (unsigned int)(*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2340));
}
unsigned int Acc_821A09F0(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2340)) == 0x0u);
}
void Acc_821A0CE0(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2476) = (unsigned char)0x0u;
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2477) = (unsigned char)0x1u;
}
void Acc_821A1108(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2476) = (unsigned char)0x1u;
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2477) = (unsigned char)0x1u;
}
void Acc_821A1120(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2472) = (unsigned int)0x0u;
}
unsigned int Acc_821A17B8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 16)) == 0x1u);
}
unsigned int Acc_821A17D0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 16)) == 0x2u);
}
unsigned int Acc_821A1C70(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 20)) == 0x0u);
}
void Acc_821A2950(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 468) = (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 468)) & 0xFFFFFFEFu);
}
unsigned int Acc_821A3708(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 24)) == 0x1u);
}
unsigned int Acc_821A3760(char* a0)
{
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    return (unsigned int)0x1u;
}
unsigned int Acc_821A3C18(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2532)) == 0xAu);
}
unsigned int Acc_821A3C30(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2532)) == 0x9u);
}
void Acc_821A3CD8(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 1392) = (unsigned int)0xFFFFFFFFu;
}
void Acc_821A3E80(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2528) = (unsigned char)0x0u;
}
unsigned int Acc_821A40E0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 468)) >> 0x1u) & 0x1u);
}
void Acc_821A4778(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
}
void Acc_821A4788(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0x1u);
}
