#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82260138(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 64)) == 0x4u);
}
void Acc_82260288(char* a0)
{
    *(unsigned char*)((char*)a0 + 145) = (unsigned char)0x0u;
}
void Acc_82261080(char* a0)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x0u;
}
void Acc_82261850(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 192) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 196) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 200) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
unsigned int Acc_822618C0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 196)) == 0x1u);
}
unsigned int Acc_822618D8(char* a0)
{
    *(unsigned int*)((char*)a0 + 196) = (unsigned int)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_822618F0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 196)) == 0x3u);
}
unsigned int Acc_82261908(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 192)) + 53)) == 0x1u);
}
unsigned int Acc_82261920(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 196)) == 0x4u);
}
unsigned int Acc_82261938(char* a0)
{
    *(unsigned int*)((char*)a0 + 196) = (unsigned int)0x2u;
    return (unsigned int)0x2u;
}
void Acc_82261A90(char* a0)
{
    *(float*)((char*)a0 + 40) = (float)(*(float*)((char*)a0 + 12));
    *(unsigned char*)((char*)a0 + 52) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)(*(unsigned int*)((char*)a0 + 24));
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)(*(unsigned int*)((char*)a0 + 28));
}
void Acc_82262E40(char* a0)
{
    *(unsigned int*)((char*)a0 + 212) = (unsigned int)0x0u;
}
void Acc_82263518(char* a0)
{
    *(unsigned int*)((char*)a0 + 320) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 336) = (unsigned int)0x0u;
}
unsigned int Acc_82264870(char* a0)
{
    return (unsigned int)((int)(short)(*(unsigned short*)((char*)a0 + 68)));
}
unsigned int Acc_82264880(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 38)) & 0x1u);
}
unsigned int Acc_82264890(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 76)) & 0x1u);
}
unsigned int Acc_82264938(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 64)) == 0x0u);
}
unsigned int Acc_82264B30(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 2264)) == 0x1u);
}
void Acc_822653A8(char* a0)
{
    *(unsigned short*)((char*)a0 + 38) = (unsigned short)0x89u;
    *(unsigned char*)((char*)a0 + 68) = (unsigned char)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 48)) & 0x1u);
    *(unsigned char*)((char*)a0 + 69) = (unsigned char)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 48)) >> 0x1u) & 0x1u);
}
void Acc_82265D48(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
}
void Acc_82265D78(char* a0)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0xFFu;
}
void Acc_82265DB0(char* a0)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0xFFu;
    *(unsigned char*)((char*)a0 + 32) = (unsigned char)0x0u;
}
void Acc_82266DE8(char* a0, char* a1)
{
    *(float*)((char*)a0 + 64) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 68) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 72) = (float)(*(float*)((char*)a1 + 8));
}
void Acc_8226C600(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 48));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 52));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 56));
}
void Acc_8226C620(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 32));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 36));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 40));
}
void Acc_8226E6A0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 48));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 52));
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 56));
}
unsigned int Acc_82270150(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 48)) + 16));
}
unsigned int Acc_82270160(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 48)) + 20));
}
unsigned int Acc_82270170(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 48)) + 1152));
}
float Acc_82270180(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 48)) + 1156));
}
void Acc_822701A8(char* a0)
{
    *(unsigned char*)((char*)a0 + 56) = (unsigned char)0x1u;
}
void Acc_822701D0(unsigned int a0, unsigned int a1)
{
    *(unsigned char*)((char*)(a1 + a0) + 57) = (unsigned char)0x1u;
}
void Acc_822701E0(unsigned int a0, unsigned int a1)
{
    *(unsigned char*)((char*)(a1 + a0) + 57) = (unsigned char)0x0u;
}
unsigned int Acc_82273B98(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 20)) + 268)) == 0x0u);
}
void Acc_82286980(char* a0)
{
    *(unsigned int*)((char*)a0 + 992) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 988) = (unsigned int)0x0u;
}
unsigned int Acc_8229ACE0(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 68)) + 176));
}
void Acc_822CF270(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)(*(unsigned int*)((char*)a2 + 20));
}
void Acc_822D0980(char* a0)
{
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)((*(unsigned char*)((char*)a0 + 8)) | 0x1u);
}
void Acc_822D0990(char* a0)
{
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)((*(unsigned char*)((char*)a0 + 8)) | 0x10u);
}
void Acc_822D09A0(char* a0)
{
    *(unsigned char*)((char*)a0 + 9) = (unsigned char)((*(unsigned char*)((char*)a0 + 9)) | 0x20u);
}
