#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_826417B0(char* a0)
{
    return (unsigned int)(*(unsigned short*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 46));
}
void Acc_82642648(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a2;
    *(unsigned char*)((char*)a0 + 104) = (unsigned char)0x1u;
}
void Acc_82642980(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a2;
    *(unsigned char*)((char*)a0 + 52) = (unsigned char)((a3 >> 0x11u) & 0x1u);
    *(unsigned char*)((char*)a0 + 53) = (unsigned char)((a3 >> 0x10u) & 0x1u);
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)a3;
}
unsigned int Acc_82642D88(unsigned int a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    return (unsigned int)((((((((a1 + a2) + ((a1 + a2) << 0x1u)) << 0x1u) + a3) + 0x3E8u) << 0x1u) + a0) << 0x2u);
}
unsigned int Acc_82643DF8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x10u;
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 160)) + 0x1Au) << 0x3u);
}
unsigned int Acc_82643E10(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x10u;
    return (unsigned int)((((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 72)) + 0xFu) & 0xFFFFFFF0u) + 0x110u);
}
unsigned int Acc_82648B88(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x1u;
    return (unsigned int)0x0u;
}
unsigned int Acc_82648BA0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x10u;
    return (unsigned int)((((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 96)) + 72)) + 0xFu) & 0xFFFFFFF0u) + 0x110u);
}
void Acc_82648D18(char* a0)
{
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)(*(unsigned int*)((char*)a0 + 32));
}
unsigned int Acc_82648D28(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x4u;
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 16)) + 0x3u) & 0xFFFFFFFCu);
}
void Acc_826494B8(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x4u;
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)0x200u;
}
void Acc_82649640(char* a0)
{
    *(unsigned int*)((char*)a0 + 152) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)0x0u;
}
void Acc_82649F98(char* a0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)(*(unsigned int*)((char*)a3 + 12));
}
void Acc_82663220(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + 0x1u);
}
unsigned int Acc_82665398(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 8)) == 0x0u);
}
void Acc_82676818(char* a0)
{
    *(unsigned short*)((char*)a0 + 32) = (unsigned short)0x0u;
    *(unsigned short*)((char*)a0 + 34) = (unsigned short)0x0u;
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
}
void Acc_82676A08(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
void Acc_82676C78(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x46u;
}
float Acc_82676DF8(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 20));
}
unsigned int Acc_8268EAC8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 4)) == 0x0u);
}
unsigned int Acc_8268EB58(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 12)) - (*(unsigned short*)((char*)a0 + 22)));
}
unsigned int Acc_82693F50(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 24)) | 0x100u);
}
void Acc_82696890(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
unsigned int Acc_82698D58(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 40)) + 36));
}
unsigned int Acc_826AEA28(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 20)) + 0x180u);
}
void Acc_826AFFE8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 92) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_826AFFF8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 96) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
unsigned int Acc_826B01F8(char* a0)
{
    return (unsigned int)(((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 20)) + 333)) >> 0x2u) & 0x1u);
}
unsigned int Acc_826B0220(char* a0)
{
    return (unsigned int)(((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 20)) + 333)) >> 0x3u) & 0x1u);
}
void Acc_826B02A0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 92));
}
void Acc_826B02B0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 96));
}
unsigned int Acc_826BCED0(char* a0)
{
    return (unsigned int)((((*(unsigned char*)((char*)a0 + 56)) == 0x0u) ^ 0x1u) + 0x1u);
}
void Acc_826BD8D8(char* a0)
{
    *(unsigned int*)((char*)a0 + 8680) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8724) = (unsigned int)0x0u;
}
void Acc_826BD8E8(char* a0)
{
    *(unsigned int*)((char*)a0 + 8796) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8840) = (unsigned int)0x0u;
}
void Acc_826BD8F8(char* a0, unsigned int a1, int unused2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 388) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 396) = (unsigned int)a3;
}
unsigned int Acc_826BDCF8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 16)) == 0x0u);
}
unsigned int Acc_826C0F08(char* a0, unsigned int a1)
{
    return (unsigned int)(((a1 + (a1 << 0x2u)) << 0x2u) + (*(unsigned int*)((char*)a0 + 16)));
}
void Acc_826C2CC0(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0xFFFFFFD1u;
}
void Acc_826C2D50(int unused0, int unused1, char* a2, float f0, float f1)
{
    *(float*)((char*)a2 + 76) = (float)f0;
    *(float*)((char*)a2 + 92) = (float)f1;
}
void Acc_826CDD80(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x0u;
}
