#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

void* Acc_82696AD0(void* p) { return (char*)p + 20; }
u32 Acc_8269E830(void* p) { return *(u32*)((char*)p + 20); }
float Acc_826A1030(void* p) { return *(float*)((char*)p + 24); }
float Acc_826A1060(void* p) { return *(float*)((char*)p + 20); }
u32 Acc_826A5EC8(void* p) { return *(u32*)((char*)p + 3464); }
u32 Acc_826A5ED0(void* p) { return *(u32*)((char*)p + 3468); }
u32 Acc_826AA260(void* p) { return *(u32*)((char*)p + 76); }
void* Acc_826AA288(void* p) { return (char*)p + 80; }
void* Acc_826AFFE0(void* p) { return (char*)p + 48; }
u32 Acc_826B0328(void* p) { return *(u32*)((char*)p + 20); }
u32 Acc_826BA290(void* p) { return *(u32*)((char*)p + 304); }
void Acc_826BB590(void* p, u32 v) { *(u32*)((char*)p + 16) = v; }
u32 Acc_826BB818(void* p) { return *(u32*)((char*)p + 48); }
u32 Acc_826C0CC8(void* p) { return *(u32*)((char*)p + 0); }
u32 Acc_826C0CD0(void* p) { return *(u32*)((char*)p + 4); }
u32 Acc_826C0DA8(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_826C0F20(void* p) { return *(u32*)((char*)p + 20); }
u32 Acc_826C0FC0(void* p) { return *(u32*)((char*)p + 28); }
u32 Acc_826C1250(void* p) { return *(u32*)((char*)p + 8); }
void Acc_826C1258(void* p, u32 v) { *(u32*)((char*)p + 8) = v; }
void Acc_826C3D80() { }
void Acc_826C3D88() { }
void Acc_826C3D90() { }
void Acc_826C3D98() { }
void Acc_826C3DA0() { }
void Acc_826C3DA8() { }
void Acc_826C3DB0() { }
void Acc_826C3DB8() { }
void Acc_826C3DC0() { }
void Acc_826C3DC8() { }
void Acc_826C3DD0() { }
void Acc_826C58C8() { }
void Acc_826C58D0() { }
void Acc_826C58D8() { }
void Acc_826C8718() { }
void Acc_826C8720() { }
u32 Acc_826D4440(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_826D4448(void* p) { return *(u32*)((char*)p + 12); }
float Acc_826D46B8(void* p) { return *(float*)((char*)p + 216); }
float Acc_826D4F58(void* p) { return *(float*)((char*)p + 68); }
