#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_825F6760(char* a0)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)((*(unsigned int*)((char*)a0 + 12)) + 0x1u);
}
unsigned int Acc_825F6798(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825F6A50(char* a0, int unused1, char* a2)
{
    *(unsigned char*)((char*)a2 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 17));
    return (unsigned int)0x0u;
}
unsigned int Acc_825F7DD0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
    *(unsigned short*)((char*)a0 + 36) = (unsigned short)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_825F8B20(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 160) = (unsigned int)a2;
    return (unsigned int)0x0u;
}
void Acc_825FC0F8(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(a0 + 0x10u);
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) << 0x4u) + (a0 + 0x10u));
}
float Acc_825FC118(char* a0)
{
    return (float)(*(float*)((char*)(((*(unsigned int*)((char*)a0 + 12)) << 0x2u) + (*(unsigned int*)((char*)a0 + 4))) + -4));
}
void Acc_825FE988(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
}
unsigned int Acc_825FECF8(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x0u;
}
void Acc_825FEEE0(char* a0)
{
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
}
void Acc_82600AC0(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a0;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a0;
}
void Acc_82600AF0(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 0));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 0)) + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 4));
}
void Acc_82600BC8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 56));
}
unsigned int Acc_82607710(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 36)) >> 0x7u);
}
unsigned int Acc_826077E8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 28)) - (*(unsigned int*)((char*)a0 + 24)));
}
unsigned int Acc_826078D8(char* a0)
{
    *(unsigned char*)((char*)a0 + 36) = (unsigned char)((*(unsigned char*)((char*)a0 + 36)) & 0x7Fu);
    return (unsigned int)0x0u;
}
unsigned int Acc_8260C880(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x1u;
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 20)) + 20));
}
void Acc_826198C0(int unused0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)((*(unsigned char*)((char*)a1 + 0)) | 0x4u);
}
void Acc_8261A170(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 0) = (unsigned int)0x7u;
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 80) = (unsigned char)0x1u;
}
void Acc_8261A4F0(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x2u;
}
void Acc_8261AC18(char* a0, char* a1, char* a2, char* a3)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 44));
    *(float*)((char*)a2 + 0) = (float)(*(float*)((char*)a0 + 48));
    *(float*)((char*)a3 + 0) = (float)(*(float*)((char*)a0 + 52));
}
void Acc_8261AC38(char* a0)
{
    *(unsigned int*)((char*)a0 + 160) = (unsigned int)0x1u;
}
unsigned int Acc_8261ACE0(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)a2;
    return (unsigned int)0x1u;
}
unsigned int Acc_8261B330(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 0)) + 172));
}
unsigned int Acc_8261B340(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) == 0x5u);
}
unsigned int Acc_8261D9F0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) == 0x3u);
}
unsigned int Acc_8261DA08(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) == 0x4u);
}
unsigned int Acc_82632220(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 172)) + (*(unsigned int*)((char*)a0 + 180)));
}
unsigned int Acc_82633910(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 32)) + 0xFFFFFFECu);
}
void Acc_82636100(char* a0, float f0)
{
    *(float*)((char*)a0 + 168) = (float)f0;
}
void Acc_82636110(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 166) = (unsigned char)(0x1u << a1);
}
unsigned int Acc_82636120(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 166)) >> 0x1u);
}
void Acc_82636928(char* a0, float f0)
{
    *(float*)((char*)a0 + 316) = (float)f0;
}
void Acc_82636938(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 314) = (unsigned char)(0x1u << a1);
}
unsigned int Acc_82636948(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 314)) >> 0x1u);
}
void Acc_82636968(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0xCu;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x80u;
}
void Acc_82636980(char* a0, float f0)
{
    *(float*)((char*)a0 + 248) = (float)f0;
}
void Acc_82639778(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
}
unsigned int Acc_8263DA58(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 16)) + 0x1B0u);
}
unsigned int Acc_8263DAD0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 16)) + 0x120u);
}
