#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_821C8970(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 88) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_821C8998(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 68));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 72));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 76));
}
void Acc_821C89B8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 80));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 84));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 88));
}
unsigned int Acc_821DC0C8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 172)) == 0x0u);
}
unsigned int Acc_821DC0E0(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 144)) == 0x0u);
}
void Acc_821F6860(char* a0)
{
    *(unsigned int*)((char*)a0 + 180) = (unsigned int)((*(unsigned int*)((char*)a0 + 180)) | 0x8u);
}
void Acc_821F6870(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 312) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 316) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 320) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_821F6D70(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
}
void Acc_821F6DA8(char* a0)
{
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)0x0u;
}
void Acc_821F94D0(char* a0)
{
    *(unsigned char*)((char*)a0 + 77) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 76) = (unsigned char)0x1u;
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
}
void Acc_821F94F0(char* a0)
{
    *(unsigned char*)((char*)a0 + 77) = (unsigned char)0x0u;
}
void Acc_821F9C10(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 100));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 104));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 108));
}
void Acc_821FC840(char* a0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a3 + 8));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a3 + 12));
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a3 + 16));
}
void Acc_821FCE88(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 124) = (unsigned char)(*(unsigned char*)((char*)a1 + 0));
}
void Acc_821FCE98(char* a0)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
}
void Acc_821FCEE0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned char*)((char*)a0 + 160) = (unsigned char)(*(unsigned char*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(float*)((char*)a0 + 156) = (float)(*(float*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 136) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
}
void Acc_821FCF40(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 20) = (unsigned char)(*(unsigned char*)((char*)a1 + 0));
}
void Acc_821FCF50(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_821FD070(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(float*)((char*)a0 + 24) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 28) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 32) = (float)(*(float*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
}
unsigned int Acc_821FD280(char* a0)
{
    return (unsigned int)(((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 116)) >> 0x4u) & 0x1u);
}
void Acc_821FD290(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_821FD300(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
}
unsigned int Acc_821FD318(char* a0)
{
    return (unsigned int)(*(unsigned char*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 156)) + 435));
}
unsigned int Acc_821FD370(char* a0)
{
    return (unsigned int)(*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 492));
}
void Acc_821FD498(char* a0)
{
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x0u;
}
void Acc_821FD570(char* a0)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
}
unsigned int Acc_821FD5B8(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 116) = (unsigned char)(((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 116)) & 0xFFu) & 0xFFFFFF9Fu);
    return (unsigned int)0x3u;
}
void Acc_821FD690(char* a0)
{
    *(unsigned char*)((char*)a0 + 592) = (unsigned char)0x1u;
}
void Acc_821FD6A0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 1316) = (unsigned char)0x0u;
}
void Acc_821FD8D0(char* a0, char* a1)
{
    *(float*)((char*)a0 + 104) = (float)(*(float*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 100) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
}
void Acc_821FD920(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(float*)((char*)a0 + 152) = (float)(*(float*)((char*)a1 + 4));
}
void Acc_821FD960(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_821FD998(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 37) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 36) = (unsigned char)(*(unsigned char*)((char*)a1 + 0));
}
void Acc_821FDDA0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned char*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(*(unsigned char*)((char*)a1 + 1));
}
void Acc_821FE010(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned char*)((char*)a1 + 0));
    *(float*)((char*)a0 + 24) = (float)(*(float*)((char*)a1 + 4));
}
void Acc_821FE0A8(char* a0)
{
    *(unsigned short*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 156)) + 74) = (unsigned short)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 156)) + 72)) & 0xFFFFu) & 0xFFFFF7FFu);
}
void Acc_821FE108(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)0x0u;
}
void Acc_821FE440(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 592) = (unsigned char)(*(unsigned char*)((char*)a1 + 40));
    *(unsigned int*)((char*)a0 + 596) = (unsigned int)((*(unsigned char*)((char*)a1 + 0)) + 0xFFFFFFFFu);
}
void Acc_821FE4A0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned char*)((char*)a1 + 0));
}
void Acc_821FE558(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 20) = (unsigned char)(*(unsigned char*)((char*)a1 + 0));
}
