#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82707E18(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 80));
}
unsigned int Acc_82707E28(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 76));
}
unsigned int Acc_82707E38(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 36));
}
unsigned int Acc_827081B0(int unused0, char* a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)a1 + 16)) & 0xFFFFFFFCu) + 0x8u);
}
void Acc_827093C0(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a1 + 79));
}
unsigned int Acc_82709C90(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 20)) + 32)) + 36));
}
unsigned int Acc_82709CA8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 16));
}
unsigned int Acc_82709CB8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 20));
}
float Acc_82709CE0(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 20)) + 32)) + 72));
}
unsigned int Acc_82709DB8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 20)) + 32)) + 44)) & 0xFFFFFFFCu) + 0x8u);
}
unsigned int Acc_82709E38(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 28)) + 20)) + 32)) + 112));
}
void Acc_82711800(char* a0, unsigned int a1, int unused2, int unused3, int unused4, int unused5, int unused6, char* a7)
{
    *(unsigned int*)((char*)a7 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 712) = (unsigned int)((*(unsigned int*)((char*)a0 + 712)) + 0x1u);
}
unsigned int Acc_82712EA8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 144)) >> 0xFu) & 0x1u);
}
unsigned int Acc_82712EE8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 144)) & 0x1u);
}
unsigned int Acc_82712EF8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 144)) >> 0xCu) & 0x1u);
}
void Acc_82712F68(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 152) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)a2;
}
unsigned int Acc_82713068(char* a0)
{
    return (unsigned int)((*(unsigned short*)((char*)a0 + 144)) & 0x3u);
}
unsigned int Acc_82715128(unsigned int a0, int unused1, unsigned int a2)
{
    return (unsigned int)((a2 - a0) == 0x0u);
}
unsigned int Acc_82715140(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 48)) == 0x0u);
}
unsigned int Acc_82715B18(int unused0, int unused1, unsigned int a2)
{
    return (unsigned int)a2;
}
unsigned int Acc_827261A8(char* a0)
{
    return (unsigned int)((int)(short)(*(unsigned short*)((char*)a0 + 14)));
}
unsigned int Acc_82727178(char* a0, unsigned int a1)
{
    return (unsigned int)((a1 << 0x2u) + (*(unsigned int*)((char*)a0 + 0)));
}
void Acc_8272C580(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
}
void Acc_8272D348(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a1 + 108));
}
unsigned int Acc_82735AF0(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    return (unsigned int)0x1u;
}
unsigned int Acc_82735F80(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x1u;
}
void Acc_827540A0(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a1 + 16));
}
void Acc_827540B0(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_827540C0(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_827543F0(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_82754400(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_82754888(char* a0)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned int*)((char*)a0 + 24)) + 0xFFFFFFFFu);
}
void Acc_82755A40(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 20));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 24));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 28));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 32));
}
unsigned int Acc_8276B1E0(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 0) = (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 0)) + 0x1u);
    return (unsigned int)(*(unsigned int*)((char*)a0 + 32));
}
void Acc_8277A8B0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 116) = (unsigned char)((*(unsigned char*)((char*)a0 + 116)) | 0x1u);
}
unsigned int Acc_8277E6F8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 16)) & 0xFFFFFFFCu) + 0x8u);
}
unsigned int Acc_8277EBA8(char* a0)
{
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x1003u;
    return (unsigned int)0x0u;
}
void Acc_8277EFF8(int unused0, char* a1, char* a2, char* a3, char* a4)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a3 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a4 + 0) = (unsigned int)0x0u;
}
void Acc_8277F010(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 72) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 76) = (unsigned int)0x0u;
}
void Acc_8277F170(char* a0, unsigned int a1)
{
    *(unsigned short*)((char*)a0 + 10) = (unsigned short)a1;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned short*)((char*)a0 + 8) = (unsigned short)0x0u;
}
