#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82128BF0(char* a0, char* a1)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 100));
    return (unsigned int)0x0u;
}
unsigned int Acc_82128C00(char* a0, float f0)
{
    *(float*)((char*)a0 + 100) = (float)f0;
    return (unsigned int)0x0u;
}
unsigned int Acc_821290F0(int unused0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)0x2u;
    *(unsigned short*)((char*)a1 + 2) = (unsigned short)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_82129108(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 12));
    return (unsigned int)0x0u;
}
unsigned int Acc_82129118(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x1Cu;
    return (unsigned int)0x0u;
}
unsigned int Acc_82129900(int unused0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)0x6u;
    *(unsigned short*)((char*)a1 + 2) = (unsigned short)0xEA6u;
    return (unsigned int)0x0u;
}
unsigned int Acc_8212CE00(int unused0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)0x6u;
    *(unsigned short*)((char*)a1 + 2) = (unsigned short)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_8212CE18(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 26));
    return (unsigned int)0x0u;
}
unsigned int Acc_8212CE28(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 26) = (unsigned char)a1;
    return (unsigned int)0x0u;
}
void Acc_8212CE50(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(a0 + 0xFFFFFFFCu);
}
unsigned int Acc_8212E638(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0x1u);
}
unsigned int Acc_8212E650(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 16)) - (*(unsigned int*)((char*)a0 + 20)));
}
void Acc_8212E8B8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(((a1 + 0x3u) & 0xFFFFFFFCu) + (*(unsigned int*)((char*)a0 + 16)));
}
unsigned int Acc_82130F08(int unused0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)0x4u;
    *(unsigned short*)((char*)a1 + 2) = (unsigned short)0xAu;
    return (unsigned int)0x0u;
}
unsigned int Acc_82134248(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 172));
    return (unsigned int)0x0u;
}
unsigned int Acc_82134258(char* a0, char* a1)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 112));
    return (unsigned int)0x0u;
}
unsigned int Acc_82134268(char* a0, char* a1)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 116));
    return (unsigned int)0x0u;
}
unsigned int Acc_82134278(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)((*(unsigned short*)((char*)a0 + 108)) * (*(unsigned int*)((char*)a0 + 120)));
    return (unsigned int)0x0u;
}
unsigned int Acc_82134368(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 168));
    return (unsigned int)0x0u;
}
unsigned int Acc_8214C310(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)((*(unsigned int*)((char*)a0 + 0)) + 0x1u);
    return (unsigned int)0x0u;
}
void Acc_8214C958(char* a0, char* a1)
{
    *(unsigned short*)((char*)a0 + 38) = (unsigned short)(*(unsigned short*)((char*)a1 + 14));
}
void Acc_8214CC58(char* a0)
{
    *(unsigned int*)((char*)a0 + 148) = (unsigned int)((*(unsigned int*)((char*)a0 + 148)) & 0xFFFFFFFEu);
}
void Acc_8214CE50(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 324) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a1 + 320) = (unsigned int)((*(unsigned int*)((char*)a1 + 320)) & 0xFFFFFFEFu);
}
void Acc_8214CF10(char* a0, float f0)
{
    *(float*)((char*)a0 + 16) = (float)f0;
}
float Acc_8214D3E8(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 56));
}
void Acc_8214D488(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 88) = (unsigned int)((a1 & 0xFFu) == 0x0u);
}
void Acc_82151240(char* a0)
{
    *(unsigned char*)((char*)a0 + 68) = (unsigned char)0x0u;
}
void Acc_82151250(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
}
void Acc_82151378(char* a0)
{
    *(unsigned char*)((char*)a0 + 5) = (unsigned char)0x0u;
}
void Acc_82151388(char* a0)
{
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 5) = (unsigned char)0x0u;
}
void Acc_82151908(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 132));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 136));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 140));
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)a0 + 144));
}
void Acc_82152088(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a3;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
}
void Acc_82155DA8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 132) = (unsigned int)a1;
    *(unsigned char*)((char*)a1 + 20) = (unsigned char)((*(unsigned char*)((char*)a1 + 20)) | 0x80u);
    *(unsigned int*)((char*)a0 + 144) = (unsigned int)((*(unsigned int*)((char*)a0 + 144)) + 0x1u);
}
void Acc_82155E50(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 136) = (unsigned int)a1;
    *(unsigned char*)((char*)a1 + 20) = (unsigned char)((*(unsigned char*)((char*)a1 + 20)) & 0x7Fu);
    *(unsigned int*)((char*)a0 + 144) = (unsigned int)((*(unsigned int*)((char*)a0 + 144)) + 0xFFFFFFFFu);
}
void Acc_82157638(char* a0, char* a1)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 28) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 32) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 36) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_82157C70(unsigned int a0, unsigned int a1, unsigned int a2)
{
    *(unsigned char*)((char*)(a1 + a0) + 2080) = (unsigned char)a2;
}
unsigned int Acc_82164440(int unused0, char* a1)
{
    return (unsigned int)((*(unsigned int*)((char*)a1 + 56)) + 0x30u);
}
unsigned int Acc_82164450(int unused0, char* a1)
{
    return (unsigned int)((*(unsigned int*)((char*)a1 + 136)) + 0x30u);
}
unsigned int Acc_8216B198(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)((a2 << 0x3u) + (*(unsigned int*)((char*)a0 + 0)));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
void Acc_8216B300(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + a1);
}
