#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82103828(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10544)) >> 0x14u) & 0xFu);
}
unsigned int Acc_82103838(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 10544)) & 0xFu);
}
unsigned int Acc_82103848(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10544)) >> 0x1Cu);
}
unsigned int Acc_82103898(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10572)) & 0x1u);
}
unsigned int Acc_82103BA0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10616)) & 0x3u);
}
unsigned int Acc_82103BD8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 10688)) & 0x1u);
}
unsigned int Acc_82103C08(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10568)) >> 0x15u) & 0x1u);
}
unsigned int Acc_82103C60(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10556)) >> 0x4u) & 0x1u);
}
unsigned int Acc_82103D70(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11860)) >> 0x14u) & 0x7u);
}
unsigned int Acc_82103DD8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11860)) >> 0x11u) & 0x7u);
}
unsigned int Acc_82103E08(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10560)) >> 0x3u) & 0x1u);
}
unsigned int Acc_82103E38(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10560)) >> 0x2u) & 0x1u);
}
unsigned int Acc_82103E68(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 10560)) >> 0x5u) & 0x1u);
}
unsigned int Acc_82103EB8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 11860)) >> 0x17u) & 0x7Fu);
}
unsigned int Acc_82104060(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned char*)((char*)(a0 + a1) + 12010)) >> 0x1u) & 0x1u);
}
unsigned int Acc_82104200(unsigned int a0, unsigned int a1)
{
    return (unsigned int)((*(unsigned char*)((char*)(a0 + a1) + 12010)) & 0x1u);
}
unsigned int Acc_82104250(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)((a1 * 0x18u) + a0) + 1164)) >> 0x17u) & 0x3u);
}
unsigned int Acc_82104300(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned char*)((char*)(a0 + a1) + 12010)) >> 0x2u) & 0x1u);
}
unsigned int Acc_82104378(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(*(unsigned char*)((char*)(a0 + a1) + 11932));
}
unsigned int Acc_82104548(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(*(unsigned char*)((char*)(a0 + a1) + 11958));
}
unsigned int Acc_821045C8(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(*(unsigned char*)((char*)(a0 + a1) + 11984));
}
unsigned int Acc_82104778(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)((a1 * 0x18u) + a0) + 1172)) >> 0x3u) & 0x3u);
}
unsigned int Acc_82104880(unsigned int a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)((a1 * 0x18u) + a0) + 1172)) >> 0x2u) & 0x1u);
}
unsigned int Acc_8210A8D8(char* a0)
{
    return (unsigned int)((((*(unsigned int*)((char*)a0 + 44)) >> 0x6u) & 0xFu) + 0x1u);
}
unsigned int Acc_8210AAA0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 36)) >> 0x1Au) + 0x1u);
}
void Acc_821117C0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(a1 & 0x1u);
    *(unsigned int*)((char*)a0 + 19892) = (unsigned int)((a1 & 0xF9u) | ((*(unsigned int*)((char*)a0 + 19892)) & 0xFFFFFF07u));
}
void Acc_821117F8(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 104) = (unsigned int)a1;
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 108) = (unsigned int)a2;
}
void Acc_82111818(char* a0, char* a1)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 356) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 360) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 364) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
unsigned int Acc_82111E70(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 116));
}
unsigned int Acc_82111E88(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 128)) + 0xFFFFFFFFu);
}
unsigned int Acc_82116458(char* a0)
{
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)((*(unsigned int*)((char*)a0 + 60)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 60)) + 0x1u);
}
unsigned int Acc_82124720(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + 0x1u);
}
unsigned int Acc_821262D8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 48));
    return (unsigned int)0x0u;
}
unsigned int Acc_821262E8(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 12));
    return (unsigned int)0x0u;
}
unsigned int Acc_821262F8(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)(a0 + 0x34u) + 0));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(a0 + 0x34u) + 4));
    return (unsigned int)0x0u;
}
unsigned int Acc_82127F28(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 61));
    return (unsigned int)0x0u;
}
unsigned int Acc_82128498(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 8));
    return (unsigned int)0x0u;
}
unsigned int Acc_821284A8(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 156));
    return (unsigned int)0x0u;
}
unsigned int Acc_82128B38(char* a0, char* a1)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 96));
    return (unsigned int)0x0u;
}
unsigned int Acc_82128B48(char* a0, float f0)
{
    *(float*)((char*)a0 + 96) = (float)f0;
    return (unsigned int)0x0u;
}
