#include "types.h"

// Single-expression accessors, 32 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_827FEC60() { }
u32 Acc_82800DF0(void* p) { return *(u32*)((char*)p + 108); }
void Acc_82806C98(void* p)
{
    VObj* q = *(VObj**)((char*)p + 24);
    q->vt->slot[1](q);
}
u32 Acc_82812138(int unused0, void* p) { return *(u32*)((char*)p + 24); }
void* Acc_82828228(void* p) { return (char*)p + 56; }
u32 Acc_82828230(void* p) { return *(u32*)((char*)p + 68); }
void Acc_8282A730(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[4](q);
}
void Acc_8282DF78() { }
void Acc_82838708() { }
void Acc_828461E8() { }
void Acc_8287E048(VObj* p) { p->vt->slot[5](p); }
void* Acc_828935E0(int unused0, void* p) { return (char*)p + 20; }
u32 Acc_82896618(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_828969C8(void* p) { return *(u32*)((char*)p + 8); }
void Acc_82897030(int unused0, void* p, u32 v) { *(u32*)((char*)p + 4) = v; }
u32 Acc_82897038(int unused0, void* p) { return *(u32*)((char*)p + 4); }
void Acc_828970D0(int unused0, void* p, u32 v) { *(u32*)((char*)p + 8) = v; }
u32 Acc_828970D8(int unused0, void* p) { return *(u32*)((char*)p + 8); }
u32 Acc_8289E780(void* p) { return *(u32*)((char*)p + 0); }
void Acc_828B166C(int unused0, void* p, int unused2, int unused3, int unused4, int unused5, u32 v) { *(u32*)((char*)p + 0) = v; }
void Acc_828B16C0() { }
u32 Acc_828C49A0(void* p) { return *(u32*)((char*)p + 160); }
u32 Acc_828C9910(void* p) { return *(u32*)((char*)p + 140); }
u32 Acc_828C9918(void* p) { return *(u32*)((char*)p + 136); }
u32 Acc_828DBF10(void* p) { return *(u32*)((char*)p + 28); }
u32 Acc_828DC5A0(void* p) { return *(u32*)((char*)p + 148); }
void Acc_828DCEC0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[10](q);
}
void Acc_828DDDE8(VObj* p) { p->vt->slot[13](p); }
u32 Acc_828DE488(void* p) { return *(u32*)((char*)p + 36); }
void Acc_828DE498(VObj* p) { p->vt->slot[9](p); }
void Acc_828F9218(void* p, u32 v) { *(u32*)((char*)p + 264) = v; }
void Acc_82903D00(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[7](q);
}
