#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_82712DC8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 36);
    q->vt->slot[18](q);
}
void Acc_82712DE0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 36);
    q->vt->slot[19](q);
}
void Acc_82712DF8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 36);
    q->vt->slot[20](q);
}
void Acc_82712E10(void* p)
{
    VObj* q = *(VObj**)((char*)p + 36);
    q->vt->slot[21](q);
}
void Acc_82712E80(VObj* p) { p->vt->slot[27](p); }
void Acc_82712E90(VObj* p) { p->vt->slot[32](p); }
u8 Acc_82712EB8(void* p) { return *(u8*)((char*)p + 150); }
void* Acc_82713338(void* p) { return (char*)p + 20; }
u32 Acc_82726190(void* p) { return *(u32*)((char*)p + 4); }
u32 Acc_82726198(void* p) { return *(u32*)((char*)p + 4); }
u32 Acc_827261A0(void* p) { return *(u32*)((char*)p + 8); }
u8 Acc_82726448(void* p) { return *(u8*)((char*)p + 13); }
u32 Acc_82727128(void* p) { return *(u32*)((char*)p + 0); }
u32 Acc_82727130(void* p) { return *(u32*)((char*)p + 0); }
u32 Acc_82727290(void* p) { return *(u32*)((char*)p + 4); }
void Acc_827311C0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[4](q);
}
void Acc_827311D8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[5](q);
}
void Acc_827351F8() { }
void Acc_82735AE8() { }
u32 Acc_82735B90(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_82736020(void* p) { return *(u32*)((char*)p + 24); }
void* Acc_8273F438(int unused0, void* p) { return (char*)p + 16; }
void* Acc_8273F440(int unused0, void* p) { return (char*)p + 16; }
void Acc_8273FC60(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[9](q);
}
void Acc_8273FC78(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[4](q);
}
void Acc_8273FC90(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[5](q);
}
void Acc_8273FCA8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[6](q);
}
void Acc_8273FCC0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[8](q);
}
void Acc_8274E570() { }
void Acc_8274E980(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[9](q);
}
void Acc_8274E998(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[10](q);
}
void Acc_8274E9B0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[11](q);
}
void Acc_8274E9C8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[12](q);
}
void Acc_8274E9E0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 12);
    q->vt->slot[13](q);
}
void* Acc_827559D8(void* p) { return (char*)p + 16; }
void Acc_827619F0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 44);
    q->vt->slot[2](q);
}
void Acc_8277A8C8(void* p, u32 v) { *(u32*)((char*)p + 40) = v; }
u8 Acc_8277E708(void* p) { return *(u8*)((char*)p + 20); }
void Acc_827820A8(void* p, int unused1, int unused2, int unused3, u32 v) { *(u32*)((char*)p + 28) = v; }
float Acc_827830B0(void* p) { return *(float*)((char*)p + 60); }
