#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void* Acc_82785020(void* p) { return (char*)p + 52; }
float Acc_82787448(void* p) { return *(float*)((char*)p + 104); }
u32 Acc_82790628(void* p) { return *(u32*)((char*)p + 120); }
u32 Acc_82790DA0(void* p) { return *(u32*)((char*)p + 68); }
u32 Acc_82792C78(void* p) { return *(u32*)((char*)p + 88); }
u32 Acc_82792E40(void* p) { return *(u32*)((char*)p + 84); }
u32 Acc_82798220(void* p) { return *(u32*)((char*)p + 44); }
void* Acc_8279A340(void* p) { return (char*)p + 16; }
u32 Acc_8279D9C8(void* p) { return *(u32*)((char*)p + 8); }
void Acc_8279F678() { }
void Acc_827A7CB0() { }
void Acc_827B30E8(VObj* p) { p->vt->slot[1](p); }
void Acc_827B3680() { }
void Acc_827B3688() { }
void Acc_827C26B0() { }
void Acc_827C26B8() { }
void Acc_827C26C0() { }
void Acc_827C26C8() { }
void Acc_827C26D0() { }
void Acc_827C3190() { }
u32 Acc_827C3250(void* p) { return *(u32*)((char*)p + 84); }
u8 Acc_827C7848(void* p) { return *(u8*)((char*)p + 9); }
u32 Acc_827DB490(void* p) { return *(u32*)((char*)p + 112); }
u32 Acc_827E9DE8(void* p) { return *(u32*)((char*)p + 2548); }
u32 Acc_827E9DF0(void* p) { return *(u32*)((char*)p + 196); }
u32 Acc_827E9DF8(void* p) { return *(u32*)((char*)p + 200); }
u32 Acc_827E9E38(void* p) { return *(u32*)((char*)p + 2552); }
void Acc_827E9E40(void* p, u32 v) { *(u32*)((char*)p + 2552) = v; }
u32 Acc_827E9E48(void* p) { return *(u32*)((char*)p + 24); }
u32 Acc_827ED498(void* p) { return *(u32*)((char*)p + 164); }
u32 Acc_827EE528(void* p) { return *(u32*)((char*)p + 128); }
void Acc_827F8688(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[8](q);
}
void Acc_827F86A0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[15](q);
}
u32 Acc_827F8EF8(void* p) { return *(u32*)((char*)p + 168); }
void* Acc_827F8F00(void* p) { return (char*)p + 208; }
u32 Acc_827F8F08(void* p) { return *(u32*)((char*)p + 192); }
u32 Acc_827F8F38(void* p) { return *(u32*)((char*)p + 160); }
void Acc_827F8F40(void* p)
{
    VObj* q = *(VObj**)((char*)p + 160);
    q->vt->slot[13](q);
}
void Acc_827FE6E8(VObj* p) { p->vt->slot[23](p); }
void Acc_827FEC50(VObj* p) { p->vt->slot[8](p); }
