#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_82782790(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 12));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 16));
}
unsigned int Acc_82783038(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 52));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 44));
}
unsigned int Acc_82783048(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 56));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 48));
}
void Acc_82783058(char* a0, char* a1, char* a2, char* a3, char* a4)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 44));
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 52));
    *(unsigned int*)((char*)a3 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 48));
    *(unsigned int*)((char*)a4 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 56));
}
void Acc_82783080(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 44));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 48));
    *(unsigned int*)((char*)a1 + 72) = (unsigned int)(*(unsigned int*)((char*)a0 + 52));
    *(unsigned int*)((char*)a1 + 76) = (unsigned int)(*(unsigned int*)((char*)a0 + 56));
}
void Acc_827830A8(char* a0, float f0)
{
    *(float*)((char*)a0 + 60) = (float)f0;
}
void Acc_827830B8(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 64));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 68));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 72));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 76));
}
void Acc_827830E0(char* a0, char* a1)
{
    *(float*)((char*)a0 + 64) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 68) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 72) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 76) = (float)(*(float*)((char*)a1 + 12));
}
void Acc_82787440(char* a0, float f0)
{
    *(float*)((char*)a0 + 104) = (float)f0;
}
void Acc_82787540(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 108));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 112));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 116));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 120));
}
void Acc_82787568(char* a0, char* a1)
{
    *(float*)((char*)a0 + 108) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 112) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 116) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 120) = (float)(*(float*)((char*)a1 + 12));
}
unsigned int Acc_82788B64(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 25)) == 0x1u);
}
void Acc_82789490(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 25) = (unsigned char)0x0u;
}
unsigned int Acc_82799C70(char* a0)
{
    return (unsigned int)((((((*(unsigned int*)((char*)a0 + 12)) << 0x9u) + ((*(unsigned int*)((char*)a0 + 28)) * 0x180u)) + (*(unsigned int*)((char*)a0 + 32))) + (*(unsigned int*)((char*)a0 + 16))) << 0x2u);
}
void Acc_8279ACA8(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
}
void Acc_827AE9B8(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x7u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x3Cu;
}
void Acc_827AF5E8(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x3u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x1Cu;
}
void Acc_827AFB30(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)0x3u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x1Cu;
}
unsigned int Acc_827B09E0(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)a0;
    return (unsigned int)0x0u;
}
unsigned int Acc_827B30E0(int unused0, int unused1, unsigned int a2)
{
    return (unsigned int)a2;
}
void Acc_827B3100(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_827B9548(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a1 + 12));
}
void Acc_827BBB18(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned int*)((char*)a0 + 24)) + 0x1u);
}
void Acc_827BBB30(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned int*)((char*)a0 + 24)) + 0xFFFFFFFFu);
}
float Acc_827C1918(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 4));
}
unsigned int Acc_827C2408(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 4));
}
unsigned int Acc_827C561C(int unused0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    return (unsigned int)a7;
}
void Acc_827DA410(char* a0)
{
    *(unsigned int*)((char*)a0 + 1) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a0 + 4));
}
void Acc_827E9E00(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 2352) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
unsigned int Acc_827E9EB0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 2844)) >> 0x12u) & 0x1u);
}
void Acc_827E9F00(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 220));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 224));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 228));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 232));
}
void Acc_827E9F28(char* a0, char* a1)
{
    *(float*)((char*)a0 + 220) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 224) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 228) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 232) = (float)(*(float*)((char*)a1 + 12));
}
float Acc_827F86D0(char* a0)
{
    return (float)(*(float*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 32)) + 72));
}
unsigned int Acc_827F86E0(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 32)) + 48));
}
unsigned int Acc_827F86F0(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 16)) + 32)) + 44)) & 0xFFFFFFFCu) + 0x8u);
}
void Acc_827F8708(char* a0, char* a1)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 28)) << 0x3u) + (*(unsigned int*)((char*)a0 + 32))) + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 28)) << 0x3u) + (*(unsigned int*)((char*)a0 + 32))) + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
}
void Acc_827F8730(char* a0, char* a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)((*(unsigned int*)((char*)a1 + 32)) + (a2 << 0x3u)) + 0));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)((*(unsigned int*)((char*)a1 + 32)) + (a2 << 0x3u)) + 4));
}
unsigned int Acc_827F8F10(char* a0)
{
    return (unsigned int)(((*(unsigned char*)((char*)a0 + 456)) >> 0x1u) & 0x1u);
}
unsigned int Acc_827FE188(int unused0, char* a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 28)) + 24)) & 0xFFFFFFFCu) + 0x8u);
}
void Acc_827FEF54(char* a0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, char* a7)
{
    *(unsigned int*)((char*)a0 + 124) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 144) = (unsigned int)((*(unsigned int*)((char*)a0 + 144)) & 0xFFF7FFFFu);
    *(unsigned int*)((char*)a7 + 0) = (unsigned int)((*(unsigned int*)((char*)a7 + 0)) | 0x400u);
}
