#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

void* Acc_82216DE0(void* p) { return (char*)p + 72; }
u8 Acc_8221E048(void* p) { return *(u8*)((char*)p + 231); }
u8 Acc_8221E050(void* p) { return *(u8*)((char*)p + 232); }
void Acc_8221E058(void* p, u8 v) { *(u8*)((char*)p + 132) = v; }
void Acc_8221E060(void* p, u32 v) { *(u32*)((char*)p + 128) = v; }
u8 Acc_8221E068(void* p) { return *(u8*)((char*)p + 132); }
float Acc_8221E0A0(void* p) { return *(float*)((char*)p + 96); }
float Acc_8221E0A8(void* p) { return *(float*)((char*)p + 100); }
float Acc_8221E0B0(void* p) { return *(float*)((char*)p + 120); }
void* Acc_82227698(void* p) { return (char*)p + 200; }
void* Acc_82228488(void* p) { return (char*)p + 132; }
float Acc_82228490(void* p) { return *(float*)((char*)p + 152); }
u32 Acc_8224BF80(void* p) { return *(u32*)((char*)p + 336); }
u32 Acc_8224BF88(void* p) { return *(u32*)((char*)p + 340); }
u8 Acc_8224C110(void* p) { return *(u8*)((char*)p + 56); }
void Acc_8224C328(void* p, u8 v) { *(u8*)((char*)p + 68) = v; }
void* Acc_8224C950(void* p) { return (char*)p + 148; }
u32 Acc_8224D1E0(void* p) { return *(u32*)((char*)p + 556); }
void Acc_8224D5A0(void* p, u32 v) { *(u32*)((char*)p + 268) = v; }
void* Acc_8224DDA0(void* p) { return (char*)p + 580; }
u32 Acc_8224DDA8(void* p) { return *(u32*)((char*)p + 112); }
void Acc_8224DE30(void* p, u32 v) { *(u32*)((char*)p + 1088) = v; }
void* Acc_8224FF08(void* p) { return (char*)p + 4; }
u8 Acc_822520E0(void* p) { return *(u8*)((char*)p + 13); }
void* Acc_82252328(void* p) { return (char*)p + 100; }
u8 Acc_8225B9D0(void* p) { return *(u8*)((char*)p + 16); }
u8 Acc_8225B9F0(void* p) { return *(u8*)((char*)p + 17); }
void* Acc_8225ECF8(void* p) { return (char*)p + 689; }
void* Acc_82261490(void* p) { return (char*)p + 144; }
void* Acc_82261870(void* p) { return (char*)p + 192; }
u32 Acc_82261E98(void* p) { return *(u32*)((char*)p + 128); }
void* Acc_82266330(void* p) { return (char*)p + 104; }
u32 Acc_82270198(void* p) { return *(u32*)((char*)p + 44); }
void Acc_822701A0(void* p, u32 v) { *(u32*)((char*)p + 44) = v; }
u32 Acc_82270210(void* p) { return *(u32*)((char*)p + 52); }
void* Acc_8228BE90(void* p) { return (char*)p + 56; }
u32 Acc_8228CF28(void* p) { return *(u32*)((char*)p + 56); }
u32 Acc_822D8898(void* p) { return *(u32*)((char*)p + 4); }
u8 Acc_822D88A0(void* p) { return *(u8*)((char*)p + 48); }
u32 Acc_82315CDC(void* p) { return *(u32*)((char*)p + 88); }
