#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_8224E068(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[38](q);
}
void Acc_8224E098(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[53](q);
}
void Acc_8224E0B0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[42](q);
}
void Acc_8224E5B8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[18](q);
}
void Acc_8224E5D0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[14](q);
}
void Acc_8224E5E8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[17](q);
}
void Acc_8224E600(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[25](q);
}
void* Acc_8224FF08(void* p) { return (char*)p + 4; }
u8 Acc_822520E0(void* p) { return *(u8*)((char*)p + 13); }
void* Acc_82252328(void* p) { return (char*)p + 100; }
void Acc_82252F48(VObj* p) { p->vt->slot[13](p); }
void Acc_82256B78(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[128](q);
}
u8 Acc_8225B9D0(void* p) { return *(u8*)((char*)p + 16); }
u8 Acc_8225B9F0(void* p) { return *(u8*)((char*)p + 17); }
void* Acc_8225ECF8(void* p) { return (char*)p + 689; }
void* Acc_82261490(void* p) { return (char*)p + 144; }
void* Acc_82261870(void* p) { return (char*)p + 192; }
u32 Acc_82261E98(void* p) { return *(u32*)((char*)p + 128); }
void* Acc_82266330(void* p) { return (char*)p + 104; }
u32 Acc_82270198(void* p) { return *(u32*)((char*)p + 44); }
void Acc_822701A0(void* p, u32 v) { *(u32*)((char*)p + 44) = v; }
u32 Acc_82270210(void* p) { return *(u32*)((char*)p + 52); }
void* Acc_8228BE90(void* p) { return (char*)p + 56; }
u32 Acc_8228CF28(void* p) { return *(u32*)((char*)p + 56); }
u32 Acc_822D8898(void* p) { return *(u32*)((char*)p + 4); }
u8 Acc_822D88A0(void* p) { return *(u8*)((char*)p + 48); }
u32 Acc_82315CDC(void* p) { return *(u32*)((char*)p + 88); }
u32 Acc_823269A0(void* p) { return *(u32*)((char*)p + 8); }
u32 Acc_82326D58(void* p) { return *(u32*)((char*)p + 24); }
u32 Acc_82349B50(void* p) { return *(u32*)((char*)p + 1364); }
void Acc_8234FE9C(void* p, int unused1, int unused2, int unused3, int unused4, int unused5, u32 v) { *(u32*)((char*)p + 4) = v; }
void Acc_82363540(VObj* p) { p->vt->slot[95](p); }
void Acc_82363550(VObj* p) { p->vt->slot[94](p); }
void Acc_823F1D60(VObj* p) { p->vt->slot[1](p); }
void Acc_823F1D90(VObj* p) { p->vt->slot[2](p); }
void Acc_823F1DA0(VObj* p) { p->vt->slot[3](p); }
u32 Acc_8240B718(void* p) { return *(u32*)((char*)p + 124); }
void* Acc_8240B720(void* p) { return (char*)p + 128; }
u32 Acc_8240B728(void* p) { return *(u32*)((char*)p + 84); }
u32 Acc_8240B730(void* p) { return *(u32*)((char*)p + 100); }
