#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_8280A430(int unused0, unsigned int a1)
{
    return (unsigned int)a1;
}
void Acc_8280CA50(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
}
void Acc_8280E658(char* a0)
{
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
}
unsigned int Acc_8282D9A0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0xCu);
}
unsigned int Acc_82832798(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 28)) + (*(unsigned int*)((char*)a0 + 20)));
}
void Acc_8283C698(char* a0)
{
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)0x1u;
}
void Acc_82846180(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
}
void Acc_82846190(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
}
void Acc_828493D0(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 16));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 20));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 24));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 28));
}
void Acc_82850A10(char* a0, unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a3;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a4;
}
void Acc_82857598(char* a0)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 141) = (unsigned char)0x0u;
}
void Acc_828575A8(char* a0)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
}
void Acc_8285B150(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
}
void Acc_8285CBE8(char* a0)
{
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
}
unsigned int Acc_82864274(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)a0;
    return (unsigned int)0x0u;
}
unsigned int Acc_828642F0(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)a0;
    return (unsigned int)0x0u;
}
void Acc_8286A7A8(char* a0)
{
    *(unsigned char*)((char*)a0 + 56) = (unsigned char)0x0u;
}
void Acc_8286B6B8(char* a0, char* a1)
{
    *(double*)((char*)a0 + 8) = (double)(*(double*)((char*)a1 + 48));
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x3u;
}
unsigned int Acc_8286C800(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 32)) + 0));
}
void Acc_8286C930(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x5u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 48));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 12) = (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 48)) + 12)) + 0x1u);
}
void Acc_8286F7A8(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x2u;
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)(*(unsigned char*)((char*)a1 + 48));
}
void Acc_8288E5E8(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 8) = (unsigned char)a2;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a3;
}
void Acc_82893570(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
}
unsigned int Acc_82896560(char* a0)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a0 + 12));
    return (unsigned int)0x0u;
}
void Acc_82896598(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_828969F8(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_82896A08(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x1u;
}
void Acc_82896FE0(int unused0, char* a1, float f0, float f1)
{
    *(float*)((char*)a1 + 0) = (float)f0;
    *(float*)((char*)a1 + 4) = (float)f1;
}
void Acc_82896FF0(int unused0, char* a1, char* a2, char* a3)
{
    *(float*)((char*)a2 + 0) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a3 + 0) = (float)(*(float*)((char*)a1 + 4));
}
unsigned int Acc_82897A38(void)
{
    return (unsigned int)(0x0u & 0xFFu);
}
void Acc_828A49D0(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)0x0u;
}
unsigned int Acc_828B3E2C(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_828BDB38(char* a0, unsigned int a1, unsigned int a2, unsigned int a3, unsigned int a4)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a3;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a4;
    return (unsigned int)0x1u;
}
void Acc_828C4B28(char* a0)
{
    *(unsigned int*)((char*)a0 + 200) = (unsigned int)0x0u;
}
unsigned int Acc_828C9660(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 48)) + 184));
}
void Acc_828CB9A0(char* a0, char* a1)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)a0 + 68));
}
unsigned int Acc_828CC4C0(int unused0, unsigned int a1)
{
    return (unsigned int)a1;
}
void Acc_828CEAB8(char* a0)
{
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)0x0u;
}
unsigned int Acc_828DE118(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 20));
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)0x1u;
    return (unsigned int)0x0u;
}
void Acc_828E00B8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x7u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x1u;
}
