#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_823FEF00(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FF060(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_8240B760(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) & 0x1u);
}
unsigned int Acc_824193D8(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
void Acc_824989D8(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 0) = (unsigned int)(*(unsigned int*)((char*)((*(unsigned int*)((char*)a0 + 0)) + 0x3CCu) + 4));
    *(unsigned int*)((char*)((*(unsigned int*)((char*)a0 + 0)) + 0x3CCu) + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 4));
}
void Acc_824CC668(char* a0)
{
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x100u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x10u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x1Fu;
}
void Acc_824CC688(char* a0)
{
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x100u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0xFu;
}
unsigned int Acc_824EC770(int unused0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a3 + 0) = (unsigned int)((a1 << 0x4u) + a2);
    return (unsigned int)0x1u;
}
unsigned int Acc_824EC788(int unused0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a3 + 0) = (unsigned int)((a1 << 0x7u) + a2);
    return (unsigned int)0x1u;
}
unsigned int Acc_824EC7A0(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0xFFFFFFFFu;
    return (unsigned int)0x1u;
}
void Acc_82504E20(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
}
unsigned int Acc_82506568(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 4)) == 0x0u);
}
unsigned int Acc_82506598(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 4)) == 0x3u);
}
unsigned int Acc_82510000(char* a0)
{
    return (unsigned int)(((a0 + 0xCu) - (*(unsigned int*)((char*)a0 + 8))) == 0x0u);
}
void Acc_82510088(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 8));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 4));
}
unsigned int Acc_82513128(char* a0, char* a1)
{
    return (unsigned int)((((((*(unsigned int*)((char*)a0 + 956)) - (*(unsigned int*)((char*)a1 + 2152))) >> 0x1Fu) + 0xFFFFFFFFu) & ((*(unsigned int*)((char*)a0 + 956)) - (*(unsigned int*)((char*)a1 + 2152)))) == 0x1u);
}
void Acc_82513340(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 168) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 132) = (unsigned char)(a1 & 0xFFu);
    *(unsigned char*)((char*)a0 + 133) = (unsigned char)(a1 & 0xFFu);
    *(unsigned char*)((char*)a0 + 134) = (unsigned char)(a1 & 0xFFu);
    *(unsigned char*)((char*)a0 + 135) = (unsigned char)(a1 & 0xFFu);
}
unsigned int Acc_82515CB8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 4));
}
unsigned int Acc_82515CC8(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 60)) + 4));
}
unsigned int Acc_82528990(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_8252DD48(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 20));
    return (unsigned int)0x0u;
}
unsigned int Acc_8253AF28(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 562) = (unsigned char)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_8253EC10(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 180) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_8253EC20(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_82545AA8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 416) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 412) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 392) = (unsigned int)((*(unsigned int*)((char*)a0 + 392)) & 0xFFFFFFFDu);
    return (unsigned int)0x0u;
}
unsigned int Acc_82547648(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 688) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_82549408(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a0 + 412) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_82582ED0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 184) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_82584428(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_82588FE0(char* a0, char* a1)
{
    *(unsigned char*)((char*)a1 + 0) = (unsigned char)((*(unsigned char*)((char*)a0 + 92)) == 0x0u);
    return (unsigned int)0x0u;
}
void Acc_8258EC58(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 56) = (unsigned int)a1;
    *(unsigned int*)((char*)a2 + 44) = (unsigned int)(*(unsigned int*)((char*)a1 + 44));
    *(unsigned int*)((char*)a1 + 44) = (unsigned int)a2;
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)((*(unsigned int*)((char*)a1 + 24)) | 0x10u);
}
unsigned int Acc_82595888(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 84));
    return (unsigned int)0x0u;
}
unsigned int Acc_82597268(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 268) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825A4140(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 0)) + 0));
}
unsigned int Acc_825AD5B0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825AD7D0(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x33u;
}
void Acc_825B82C8(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a2;
}
void Acc_825B8330(char* a0)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
}
void Acc_825B8340(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a2;
}
void Acc_825B8390(char* a0, float f0)
{
    *(float*)((char*)a0 + 0) = (float)f0;
}
