#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

void Acc_826FCB38(void* p, u32 v) { *(u32*)((char*)p + 92) = v; }
u32 Acc_82700058(void* p) { return *(u32*)((char*)p + 52); }
u8 Acc_82712EB8(void* p) { return *(u8*)((char*)p + 150); }
void* Acc_82713338(void* p) { return (char*)p + 20; }
u32 Acc_82726190(void* p) { return *(u32*)((char*)p + 4); }
u32 Acc_82726198(void* p) { return *(u32*)((char*)p + 4); }
u32 Acc_827261A0(void* p) { return *(u32*)((char*)p + 8); }
u8 Acc_82726448(void* p) { return *(u8*)((char*)p + 13); }
u32 Acc_82727128(void* p) { return *(u32*)((char*)p + 0); }
u32 Acc_82727130(void* p) { return *(u32*)((char*)p + 0); }
u32 Acc_82727290(void* p) { return *(u32*)((char*)p + 4); }
void Acc_827351F8() { }
void Acc_82735AE8() { }
u32 Acc_82735B90(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_82736020(void* p) { return *(u32*)((char*)p + 24); }
void* Acc_8273F438(int unused0, void* p) { return (char*)p + 16; }
void* Acc_8273F440(int unused0, void* p) { return (char*)p + 16; }
void Acc_8274E570() { }
void* Acc_827559D8(void* p) { return (char*)p + 16; }
void Acc_8277A8C8(void* p, u32 v) { *(u32*)((char*)p + 40) = v; }
u8 Acc_8277E708(void* p) { return *(u8*)((char*)p + 20); }
void Acc_827820A8(void* p, int unused1, int unused2, int unused3, u32 v) { *(u32*)((char*)p + 28) = v; }
float Acc_827830B0(void* p) { return *(float*)((char*)p + 60); }
void* Acc_82785020(void* p) { return (char*)p + 52; }
float Acc_82787448(void* p) { return *(float*)((char*)p + 104); }
u32 Acc_82790628(void* p) { return *(u32*)((char*)p + 120); }
u32 Acc_82790DA0(void* p) { return *(u32*)((char*)p + 68); }
u32 Acc_82792C78(void* p) { return *(u32*)((char*)p + 88); }
u32 Acc_82792E40(void* p) { return *(u32*)((char*)p + 84); }
u32 Acc_82798220(void* p) { return *(u32*)((char*)p + 44); }
void* Acc_8279A340(void* p) { return (char*)p + 16; }
u32 Acc_8279D9C8(void* p) { return *(u32*)((char*)p + 8); }
void Acc_8279F678() { }
void Acc_827A7CB0() { }
void Acc_827B3680() { }
void Acc_827B3688() { }
void Acc_827C26B0() { }
void Acc_827C26B8() { }
void Acc_827C26C0() { }
void Acc_827C26C8() { }
