#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

u32 Acc_826D8E30(void* p) { return *(u32*)((char*)p + 520); }
void Acc_826DD3F0() { }
void Acc_826DD430() { }
void Acc_826E6E28() { }
void Acc_826EA370(void* p, u8 v) { *(u8*)((char*)p + 7715) = v; }
void Acc_826EC0D0() { }
void Acc_826ED6A8() { }
u32 Acc_826FAA38(void* p) { return *(u32*)((char*)p + 8); }
u32 Acc_826FAEB0(void* p) { return *(u32*)((char*)p + 8); }
u32 Acc_826FAEB8(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_826FAFB0(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_826FB468(void* p) { return *(u32*)((char*)p + 36); }
void Acc_826FC918() { }
void Acc_826FC960() { }
void Acc_826FC968() { }
void Acc_826FC970() { }
void Acc_826FC978() { }
void Acc_826FC980() { }
void Acc_826FC988() { }
void Acc_826FC990() { }
void Acc_826FC998() { }
void Acc_826FC9A0() { }
void Acc_826FC9A8() { }
void Acc_826FC9B0() { }
void Acc_826FC9B8() { }
void Acc_826FC9C0() { }
void Acc_826FC9C8() { }
void Acc_826FC9D0() { }
void Acc_826FC9D8() { }
void Acc_826FC9E0() { }
void Acc_826FC9E8() { }
void Acc_826FC9F0() { }
void Acc_826FC9F8() { }
void Acc_826FCA00() { }
void Acc_826FCA08() { }
void Acc_826FCA10() { }
void Acc_826FCA18() { }
void Acc_826FCA20() { }
void Acc_826FCA28() { }
void Acc_826FCA30() { }
