#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_825B9D60(char* a0)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
    return (unsigned int)0x1u;
}
void Acc_825B9D80(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)(a1 & 0xFFFFu);
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)(*(unsigned int*)((char*)a0 + 20));
}
unsigned int Acc_825B9E48(char* a0)
{
    return (unsigned int)((((((*(unsigned int*)((char*)a0 + 8)) - (*(unsigned int*)((char*)a0 + 16))) << 0x2u) + (*(unsigned int*)((char*)a0 + 12))) << 0x3u) - (*(unsigned int*)((char*)a0 + 20)));
}
void Acc_825BD768(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x2u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
}
unsigned int Acc_825C6320(char* a0)
{
    return (unsigned int)((((0x1u << (*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 168)) + 28))) + 0xFFFFFFFFu) - (*(unsigned int*)((char*)a0 + 104))) == 0x0u);
}
unsigned int Acc_825C64A8(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 96)) >> 0x11u) & 0x1u);
}
unsigned int Acc_825C64D8(char* a0)
{
    return (unsigned int)(((*(unsigned short*)((char*)a0 + 100)) >> 0x5u) & 0x1u);
}
unsigned int Acc_825C9C78(char* a0, float f0)
{
    *(float*)((char*)a0 + 128) = (float)f0;
    return (unsigned int)0x0u;
}
unsigned int Acc_825C9CA8(char* a0, float f0)
{
    *(float*)((char*)a0 + 132) = (float)f0;
    return (unsigned int)0x0u;
}
unsigned int Acc_825CA4E0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 124) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825CE250(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825D74D0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825DA400(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825DE948(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
void Acc_825DF470(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x64u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
}
void Acc_825DF4C0(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x64u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x2u;
}
void Acc_825DF4D8(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x64u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x3u;
}
unsigned int Acc_825DF580(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) >> 0x2u) & 0x7u);
}
void Acc_825DF590(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) & 0xFFFFFFE3u) | (a1 << 0x2u));
}
void Acc_825DF5A8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) & 0xFFFFFFFDu) | (a1 << 0x1u));
}
void Acc_825DF5C0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) & 0xFFFFFFFEu) | a1);
}
unsigned int Acc_825E0440(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 36)) >> 0x5u) & 0x1u);
}
unsigned int Acc_825E2890(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 52) = (unsigned char)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_825E3078(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825E3110(char* a0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a3;
    *(unsigned int*)((char*)a3 + 8) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
void Acc_825E4538(char* a0, float f0)
{
    *(float*)((char*)a0 + 8) = (float)f0;
}
void Acc_825E5140(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)(*(unsigned char*)((char*)a1 + 20));
    *(unsigned char*)((char*)a0 + 1) = (unsigned char)(*(unsigned char*)((char*)a1 + 21));
}
void Acc_825E7658(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 28));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 32));
}
unsigned int Acc_825E96D0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825E9800(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 160) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825EB030(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 104) = (unsigned int)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_825EC9D0(int unused0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_825ECE58(int unused0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)0x0u;
    return (unsigned int)0x25u;
}
unsigned int Acc_825ED2B0(char* a0, int unused1, char* a2)
{
    *(unsigned char*)((char*)a2 + 0) = (unsigned char)((*(unsigned int*)((char*)a0 + 12)) & 0x1u);
    return (unsigned int)0x0u;
}
unsigned int Acc_825ED2C8(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 60));
    return (unsigned int)0x0u;
}
unsigned int Acc_825ED2E0(char* a0, int unused1, char* a2)
{
    *(float*)((char*)a2 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 148));
    return (unsigned int)0x0u;
}
unsigned int Acc_825ED320(int unused0, int unused1, char* a2)
{
    *(unsigned char*)((char*)a2 + 0) = (unsigned char)0x0u;
    return (unsigned int)0x0u;
}
unsigned int Acc_825ED330(char* a0, int unused1, int unused2, char* a3)
{
    *(unsigned int*)((char*)a3 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 16));
    return (unsigned int)0x0u;
}
unsigned int Acc_825F2498(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 24)) + 40));
    return (unsigned int)0x0u;
}
unsigned int Acc_825F53C8(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 152) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)a2;
    return (unsigned int)0x0u;
}
