#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

void* Acc_8260C7C0(void* p) { return (char*)p + 36; }
void* Acc_8261AC10(void* p) { return (char*)p + 64; }
void Acc_8261AC60(void* p, u32 v) { *(u32*)((char*)p + 28) = v; }
void* Acc_8261AD98(void* p) { return (char*)p + 92; }
void* Acc_8261ADA0(void* p) { return (char*)p + 48; }
u32 Acc_8261B8E0(void* p) { return *(u32*)((char*)p + 104); }
void Acc_8261B8E8(void* p, u32 v) { *(u32*)((char*)p + 104) = v; }
void Acc_8262FD68() { }
void Acc_826319D0(void* p, u8 v) { *(u8*)((char*)p + 190) = v; }
void* Acc_826337A8(void* p) { return (char*)p + 68; }
float Acc_82636108(void* p) { return *(float*)((char*)p + 168); }
float Acc_82636930(void* p) { return *(float*)((char*)p + 316); }
u32 Acc_826369A0(void* p) { return *(u32*)((char*)p + 224); }
u32 Acc_82636A50(void* p) { return *(u32*)((char*)p + 232); }
u32 Acc_82636AB0(void* p) { return *(u32*)((char*)p + 228); }
void* Acc_82639C20(void* p) { return (char*)p + 116; }
void* Acc_82639C50(void* p) { return (char*)p + 16; }
u32 Acc_82641A40(void* p) { return *(u32*)((char*)p + 60); }
void Acc_82642F28(void* p, u32 v) { *(u32*)((char*)p + 64) = v; }
void* Acc_82648B98(void* p) { return (char*)p + 16; }
void Acc_82662930(void* p, u32 v) { *(u32*)((char*)p + 20) = v; }
u8 Acc_82663880(void* p) { return *(u8*)((char*)p + 24); }
void Acc_82667708() { }
void Acc_82667710() { }
void* Acc_8267F0E0(void* p) { return (char*)p + 8; }
void* Acc_826813E0(void* p) { return (char*)p + 160; }
float Acc_82681760(void* p) { return *(float*)((char*)p + 20); }
void Acc_8268FFC0() { }
void Acc_826903D8() { }
void Acc_826904A8() { }
void Acc_82690698() { }
void Acc_82690748() { }
void Acc_826908D8() { }
void Acc_826909B0() { }
void Acc_82690BC0() { }
void Acc_826911B8() { }
void Acc_826911C0() { }
void Acc_826911C8() { }
float Acc_82691B68(void* p) { return *(float*)((char*)p + 20); }
u32 Acc_826969B0(void* p) { return *(u32*)((char*)p + 4); }
