#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

u32 Acc_82102D60(void* p) { return *(u32*)((char*)p + 11884); }
u32 Acc_82102E08(void* p) { return *(u32*)((char*)p + 11888); }
u8 Acc_82103000(void* p) { return *(u8*)((char*)p + 10499); }
u8 Acc_82103020(void* p) { return *(u8*)((char*)p + 10498); }
u8 Acc_82103040(void* p) { return *(u8*)((char*)p + 10497); }
u8 Acc_82103060(void* p) { return *(u8*)((char*)p + 10495); }
u8 Acc_82103080(void* p) { return *(u8*)((char*)p + 10494); }
u8 Acc_821030A0(void* p) { return *(u8*)((char*)p + 10493); }
u32 Acc_82103110(void* p) { return *(u32*)((char*)p + 11864); }
u32 Acc_821032D0(void* p) { return *(u32*)((char*)p + 10752); }
u32 Acc_82103310(void* p) { return *(u32*)((char*)p + 11868); }
u32 Acc_82103350(void* p) { return *(u32*)((char*)p + 11872); }
u32 Acc_82103390(void* p) { return *(u32*)((char*)p + 11876); }
u32 Acc_821033D0(void* p) { return *(u32*)((char*)p + 11880); }
void Acc_821033D8(void* p, u32 v) { *(u32*)((char*)p + 11892) = v; }
u32 Acc_821033E0(void* p) { return *(u32*)((char*)p + 11892); }
u32 Acc_82103938(void* p) { return *(u32*)((char*)p + 12036); }
u32 Acc_821039D0(void* p) { return *(u32*)((char*)p + 12040); }
u32 Acc_82103A68(void* p) { return *(u32*)((char*)p + 12044); }
u32 Acc_82103B00(void* p) { return *(u32*)((char*)p + 12048); }
u32 Acc_82103C38(void* p) { return *(u32*)((char*)p + 10456); }
u8 Acc_82103C90(void* p) { return *(u8*)((char*)p + 10556); }
u32 Acc_82103CC0(void* p) { return *(u32*)((char*)p + 10700); }
u32 Acc_82103CF0(void* p) { return *(u32*)((char*)p + 10692); }
u32 Acc_82103D18(void* p) { return *(u32*)((char*)p + 10704); }
u32 Acc_82103D48(void* p) { return *(u32*)((char*)p + 10696); }
u8 Acc_82103E90(void* p) { return *(u8*)((char*)p + 10562); }
void Acc_82103E98(void* p, u32 v) { *(u32*)((char*)p + 13596) = v; }
u32 Acc_82103EA0(void* p) { return *(u32*)((char*)p + 13596); }
void Acc_82109530(int unused0, int unused1, int unused2, void* p, int unused4, int unused5, u32 v) { *(u32*)((char*)p + 0) = v; }
void Acc_821346A0(u32 v, void* p) { *(u32*)((char*)p + 0) = v; }
void Acc_8214C890(VObj* p) { p->vt->slot[23](p); }
float Acc_8214CF30(void* p) { return *(float*)((char*)p + 8); }
void Acc_8214D228(void* p)
{
    VObj* q = *(VObj**)((char*)p + 332);
    q->vt->slot[15](q);
}
u32 Acc_8214FD98(void* p) { return *(u32*)((char*)p + 108); }
void Acc_8214FDA0(void* p, u32 v) { *(u32*)((char*)p + 108) = v; }
void* Acc_821501C0(int unused0, void* p) { return (char*)p + 232; }
void* Acc_821501F0(int unused0, void* p) { return (char*)p + 1416; }
void* Acc_821501F8(int unused0, void* p) { return (char*)p + 152; }
u32 Acc_82150200(int unused0, void* p) { return *(u32*)((char*)p + 92); }
