#include "types.h"

// Single-expression accessors, 7 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_828F85F8(char* a0)
{
    *(unsigned int*)((char*)a0 + 156) = (unsigned int)((*(unsigned int*)((char*)a0 + 156)) + 0x1u);
}
void Acc_828F8608(char* a0)
{
    *(unsigned int*)((char*)a0 + 116) = (unsigned int)0x0u;
}
unsigned int Acc_828F8680(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 116)) == 0x0u);
}
void Acc_828F8690(char* a0)
{
    *(unsigned int*)((char*)a0 + 116) = (unsigned int)0x1u;
}
unsigned int Acc_828F9410(int unused0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    return (unsigned int)a7;
}
void Acc_82903718(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
}
unsigned int Acc_82903ED4(int unused0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    return (unsigned int)a7;
}
