#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_821F97C0(void* p, u32 v) { *(u32*)((char*)p + 8) = v; }
u32 Acc_821F9910(void* p) { return *(u32*)((char*)p + 0); }
void Acc_821FD130(VObj* p) { p->vt->slot[5](p); }
void Acc_821FD140(void* p, u32 v) { *(u32*)((char*)p + 20) = v; }
u32 Acc_822015E0(void* p) { return *(u32*)((char*)p + 584); }
u32 Acc_82202208(void* p) { return *(u32*)((char*)p + 480); }
void Acc_82202658(void* p, u32 v) { *(u32*)((char*)p + 52) = v; }
u32 Acc_822158C0(void* p) { return *(u32*)((char*)p + 416); }
void* Acc_82216DA0(void* p) { return (char*)p + 3912; }
void Acc_82216DA8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[31](q);
}
void Acc_82216DC0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 4);
    q->vt->slot[30](q);
}
float Acc_82216DD8(void* p) { return *(float*)((char*)p + 5192); }
void* Acc_82216DE0(void* p) { return (char*)p + 72; }
void Acc_82219748(VObj* p) { p->vt->slot[21](p); }
void Acc_82219758(VObj* p) { p->vt->slot[22](p); }
void Acc_82219768(VObj* p) { p->vt->slot[25](p); }
void Acc_82219778(VObj* p) { p->vt->slot[26](p); }
u8 Acc_8221E048(void* p) { return *(u8*)((char*)p + 231); }
u8 Acc_8221E050(void* p) { return *(u8*)((char*)p + 232); }
void Acc_8221E058(void* p, u8 v) { *(u8*)((char*)p + 132) = v; }
void Acc_8221E060(void* p, u32 v) { *(u32*)((char*)p + 128) = v; }
u8 Acc_8221E068(void* p) { return *(u8*)((char*)p + 132); }
float Acc_8221E0A0(void* p) { return *(float*)((char*)p + 96); }
float Acc_8221E0A8(void* p) { return *(float*)((char*)p + 100); }
float Acc_8221E0B0(void* p) { return *(float*)((char*)p + 120); }
void* Acc_82227698(void* p) { return (char*)p + 200; }
void* Acc_82228488(void* p) { return (char*)p + 132; }
float Acc_82228490(void* p) { return *(float*)((char*)p + 152); }
void Acc_8224BD10(VObj* p) { p->vt->slot[2](p); }
u32 Acc_8224BF80(void* p) { return *(u32*)((char*)p + 336); }
u32 Acc_8224BF88(void* p) { return *(u32*)((char*)p + 340); }
u8 Acc_8224C110(void* p) { return *(u8*)((char*)p + 56); }
void Acc_8224C328(void* p, u8 v) { *(u8*)((char*)p + 68) = v; }
void* Acc_8224C950(void* p) { return (char*)p + 148; }
u32 Acc_8224D1E0(void* p) { return *(u32*)((char*)p + 556); }
void Acc_8224D5A0(void* p, u32 v) { *(u32*)((char*)p + 268) = v; }
void* Acc_8224DDA0(void* p) { return (char*)p + 580; }
u32 Acc_8224DDA8(void* p) { return *(u32*)((char*)p + 112); }
void Acc_8224DE30(void* p, u32 v) { *(u32*)((char*)p + 1088) = v; }
void Acc_8224E050(void* p)
{
    VObj* q = *(VObj**)((char*)p + 8);
    q->vt->slot[44](q);
}
