#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_821117C0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(a1 & 0x1u);
    *(unsigned int*)((char*)a0 + 19892) = (unsigned int)((a1 & 0xF9u) | ((*(unsigned int*)((char*)a0 + 19892)) & 0xFFFFFF07u));
}
void Acc_821117F8(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 104) = (unsigned int)a1;
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 108) = (unsigned int)a2;
}
void Acc_82111818(char* a0, char* a1)
{
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 356) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 360) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)(((*(unsigned int*)((char*)a0 + 0)) * 0x26D0u) + a0) + 364) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
unsigned int Acc_82116458(char* a0)
{
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)((*(unsigned int*)((char*)a0 + 60)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 60)) + 0x1u);
}
unsigned int Acc_82124720(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + 0x1u);
}
unsigned int Acc_821262F8(unsigned int a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)(a0 + 0x34u) + 0));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(a0 + 0x34u) + 4));
    return (unsigned int)0x0u;
}
unsigned int Acc_8212CE28(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 26) = (unsigned char)a1;
    return (unsigned int)0x0u;
}
unsigned int Acc_8212E638(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0x1u);
}
void Acc_8214D348(char* a0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 324) = (unsigned int)a0;
    *(unsigned int*)((char*)a1 + 324) = (unsigned int)a0;
    *(unsigned int*)((char*)a1 + 320) = (unsigned int)((*(unsigned int*)((char*)a1 + 320)) | 0x10u);
    *(unsigned int*)((char*)a2 + 320) = (unsigned int)((*(unsigned int*)((char*)a2 + 320)) | 0x10u);
    *(unsigned int*)((char*)a0 + 320) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a0 + 328) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 332) = (unsigned int)a2;
}
unsigned int Acc_82150FD8(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)((*(unsigned int*)((char*)a1 + 0)) | 0x1u);
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)a0 + 100));
    *(unsigned int*)((char*)a0 + 100) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 81) = (unsigned char)((*(unsigned char*)((char*)a0 + 81)) + 0x1u);
    return (unsigned int)(*(unsigned char*)((char*)a0 + 81));
}
void Acc_82151908(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 132));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 136));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 140));
    *(unsigned int*)((char*)a1 + 12) = (unsigned int)(*(unsigned int*)((char*)a0 + 144));
}
void Acc_82157638(char* a0, char* a1)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 28) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 32) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 72)) + 36) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_82157C70(unsigned int a0, unsigned int a1, unsigned int a2)
{
    *(unsigned char*)((char*)(a1 + a0) + 2080) = (unsigned char)a2;
}
void Acc_82157FD0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)a0 + 0));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)a0 + 4));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)a0 + 8));
    *(unsigned int*)((char*)a1 + 16) = (unsigned int)(*(unsigned int*)((char*)a0 + 16));
    *(unsigned int*)((char*)a1 + 20) = (unsigned int)(*(unsigned int*)((char*)a0 + 20));
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)(*(unsigned int*)((char*)a0 + 24));
    *(unsigned int*)((char*)a1 + 32) = (unsigned int)(*(unsigned int*)((char*)a0 + 32));
    *(unsigned int*)((char*)a1 + 36) = (unsigned int)(*(unsigned int*)((char*)a0 + 36));
    *(unsigned int*)((char*)a1 + 40) = (unsigned int)(*(unsigned int*)((char*)a0 + 40));
    *(unsigned int*)((char*)a1 + 48) = (unsigned int)(*(unsigned int*)((char*)a0 + 48));
    *(unsigned int*)((char*)a1 + 52) = (unsigned int)(*(unsigned int*)((char*)a0 + 52));
    *(unsigned int*)((char*)a1 + 56) = (unsigned int)(*(unsigned int*)((char*)a0 + 56));
}
unsigned int Acc_8216B198(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)((a2 << 0x3u) + (*(unsigned int*)((char*)a0 + 0)));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
void Acc_8216B300(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + a1);
}
void Acc_8216B318(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)((*(unsigned int*)((char*)a0 + 32)) + a1);
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 40)));
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)((*(unsigned int*)((char*)a0 + 48)) + a1);
}
void Acc_8216B340(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)((*(unsigned int*)((char*)a0 + 16)) + a1);
}
void Acc_8216B360(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)((*(unsigned int*)((char*)a0 + 12)) + a1);
}
void Acc_8216B378(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)((*(unsigned int*)((char*)a0 + 36)) + a1);
}
void Acc_8216B388(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 72) = (unsigned int)((*(unsigned int*)((char*)a0 + 72)) + a1);
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 76)));
}
void Acc_8216B3E8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)((*(unsigned int*)((char*)a0 + 40)) + a1);
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 44)));
}
void Acc_8216B470(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)((*(unsigned int*)((char*)a0 + 68)) + a1);
}
void Acc_8216B480(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)((*(unsigned int*)((char*)a0 + 4)) + a1);
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(a1 + (*(unsigned int*)((char*)a0 + 12)));
}
void Acc_8216B4F8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + a1);
}
void Acc_8216B508(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 272) = (unsigned int)((*(unsigned int*)((char*)a0 + 272)) + a1);
}
void Acc_8219E3D0(char* a0)
{
    *(unsigned int*)((char*)a0 + 452) = (unsigned int)(*(unsigned int*)((char*)a0 + 448));
    *(unsigned int*)((char*)a0 + 448) = (unsigned int)(*(unsigned int*)((char*)a0 + 452));
}
void Acc_821A6290(char* a0, char* a1, float f0, float f1)
{
    *(unsigned char*)((char*)a0 + 352) = (unsigned char)0x1u;
    *(unsigned int*)((char*)a0 + 328) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 332) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 336) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(float*)((char*)a0 + 344) = (float)f0;
    *(float*)((char*)a0 + 348) = (float)f1;
    *(unsigned int*)((char*)a0 + 340) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_821AAE28(char* a0, char* a1, int unused2, unsigned int a3, float f0)
{
    *(unsigned char*)((char*)a0 + 1816) = (unsigned char)0x1u;
    *(float*)((char*)a0 + 1820) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 1824) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 1828) = (float)(*(float*)((char*)a1 + 8));
    *(unsigned char*)((char*)a0 + 1817) = (unsigned char)a3;
    *(float*)((char*)a0 + 1832) = (float)f0;
}
void Acc_821AD448(char* a0)
{
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 16));
    *(unsigned int*)((char*)a0 + 72) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 20));
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 24));
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 28));
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 32));
    *(unsigned int*)((char*)a0 + 88) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 36));
}
void Acc_821AE988(char* a0)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 240) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 236) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 448) = (unsigned int)(a0 + 0x18u);
    *(unsigned int*)((char*)a0 + 452) = (unsigned int)(a0 + 0xECu);
}
void Acc_821AED50(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 48));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 52));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 56));
}
void Acc_821FCF50(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
}
void Acc_821FD070(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(float*)((char*)a0 + 24) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 28) = (float)(*(float*)((char*)a1 + 8));
    *(float*)((char*)a0 + 32) = (float)(*(float*)((char*)a1 + 12));
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)(*(unsigned int*)((char*)a1 + 16));
}
void Acc_821FD998(char* a0, char* a1)
{
    *(unsigned char*)((char*)a0 + 37) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 36) = (unsigned char)(*(unsigned char*)((char*)a1 + 0));
}
void Acc_82201090(int unused0, char* a1, char* a2)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 60));
    *(float*)((char*)a1 + 4) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 64));
    *(float*)((char*)a1 + 8) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a2 + 100)) + 68));
}
unsigned int Acc_82201638(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 60));
    *(unsigned int*)((char*)a1 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 64));
    *(unsigned int*)((char*)a1 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 100)) + 68));
    return (unsigned int)0x1u;
}
void Acc_82202468(char* a0, char* a1)
{
    *(float*)((char*)a0 + 0) = (float)(*(float*)((char*)a1 + 60));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a1 + 64));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a1 + 68));
    *(float*)((char*)a0 + 12) = (float)(*(float*)((char*)a1 + 48));
    *(float*)((char*)a0 + 16) = (float)(*(float*)((char*)a1 + 52));
    *(float*)((char*)a0 + 20) = (float)(*(float*)((char*)a1 + 56));
}
void Acc_82202D68(char* a0)
{
    *(unsigned char*)((char*)a0 + 125) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 56) = (unsigned char)(*(unsigned char*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 196)) + 124)) + 0)) + 144));
}
unsigned int Acc_82219038(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(((a2 + (a2 << 0x1u)) << 0x2u) + (*(unsigned int*)((char*)a0 + 0)));
    return (unsigned int)(*(unsigned int*)((char*)a0 + 0));
}
