#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_82253690(char* a0)
{
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 12)) + 292));
}
void Acc_82254A38(char* a0)
{
    *(unsigned char*)((char*)a0 + 2273) = (unsigned char)0x1u;
}
void Acc_82254B88(char* a0)
{
    *(unsigned char*)((char*)a0 + 2412) = (unsigned char)0x1u;
}
void Acc_82254BF8(char* a0)
{
    *(unsigned char*)((char*)a0 + 2413) = (unsigned char)0x1u;
}
void Acc_82254C58(char* a0)
{
    *(unsigned char*)((char*)a0 + 2415) = (unsigned char)0x1u;
}
void Acc_82254C68(char* a0)
{
    *(unsigned char*)((char*)a0 + 2415) = (unsigned char)0x0u;
}
void Acc_82254C78(char* a0)
{
    *(unsigned char*)((char*)a0 + 2414) = (unsigned char)0x1u;
}
unsigned int Acc_82255868(char* a0)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x4u;
    return (unsigned int)0x0u;
}
void Acc_822563C8(char* a0)
{
    *(unsigned char*)((char*)a0 + 28) = (unsigned char)0x0u;
}
void Acc_82256838(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2437) = (unsigned char)0x1u;
}
unsigned int Acc_822568E8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2436)) == 0x0u);
}
void Acc_82256E90(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2585) = (unsigned char)0x0u;
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2586) = (unsigned char)0x1u;
}
void Acc_822573A8(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2585) = (unsigned char)0x1u;
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2586) = (unsigned char)0x1u;
}
void Acc_822573C0(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2572) = (unsigned int)0x0u;
}
void Acc_82257E78(char* a0)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
}
unsigned int Acc_82258160(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x1u;
    return (unsigned int)0x1u;
}
unsigned int Acc_82258178(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x0u;
    return (unsigned int)0x1u;
}
unsigned int Acc_82258780(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 28)) == 0x0u);
}
void Acc_822587D8(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x0u;
}
void Acc_82259F80(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x2u;
}
void Acc_8225A1F0(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x1u;
}
void Acc_8225A368(char* a0)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2288) = (unsigned int)0x3u;
}
unsigned int Acc_8225B0E8(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)a0 + 28)) == 0x1u);
}
unsigned int Acc_8225B130(char* a0)
{
    *(unsigned char*)((char*)a0 + 28) = (unsigned char)0x0u;
    return (unsigned int)0x1u;
}
void Acc_8225B9C0(char* a0)
{
    *(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2660) = (unsigned char)0x0u;
}
unsigned int Acc_8225B9D8(char* a0)
{
    *(unsigned char*)((char*)a0 + 16) = (unsigned char)0x0u;
    return (unsigned int)0x0u;
}
void Acc_8225BB08(char* a0)
{
    *(unsigned char*)((char*)a0 + 16) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 28) = (unsigned char)0x0u;
}
unsigned int Acc_8225C110(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x1u);
}
unsigned int Acc_8225C128(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x2u);
}
unsigned int Acc_8225C140(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x3u);
}
unsigned int Acc_8225C158(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x4u);
}
unsigned int Acc_8225C170(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x5u);
}
unsigned int Acc_8225C188(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x6u);
}
unsigned int Acc_8225C1A0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x7u);
}
unsigned int Acc_8225C1B8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x8u);
}
unsigned int Acc_8225C1D0(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 2240)) == 0x9u);
}
void Acc_8225FDF0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a1 + 12));
}
void Acc_8225FF00(char* a0)
{
    *(unsigned char*)((char*)a0 + 68) = (unsigned char)0x1u;
}
unsigned int Acc_8225FFD0(char* a0)
{
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)((*(unsigned int*)((char*)a0 + 76)) + 0x1u);
    return (unsigned int)0x1u;
}
unsigned int Acc_82260120(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 64)) == 0x1u);
}
