#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

unsigned int Acc_822D0DB0(char* a0, unsigned int a1)
{
    return (unsigned int)((a1 - ((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 76)) + 80)) + 0xFFFFFFFFu)) == 0x0u);
}
void Acc_822D1E90(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 1) = (unsigned char)0x3u;
    *(unsigned char*)((char*)a0 + 2) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
}
void Acc_822D1EB0(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
}
void Acc_822D1ED8(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0xFFFFFFFFu;
}
void Acc_822D3AA0(char* a0)
{
    *(unsigned char*)((char*)a0 + 40) = (unsigned char)0x0u;
}
void Acc_822D3AB0(char* a0)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x1u;
}
unsigned int Acc_822D3AC0(char* a0)
{
    return (unsigned int)(*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + -188)) + 217));
}
unsigned int Acc_822D3F30(char* a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 20)) + 0xFFFFFFFFu) & a1);
}
void Acc_822D4098(char* a0)
{
    *(unsigned char*)((char*)a0 + 48) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x0u;
}
void Acc_822D40D0(char* a0)
{
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 84) = (unsigned char)0x1u;
    *(unsigned char*)((char*)a0 + 76) = (unsigned char)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 32)) & 0x1u);
}
void Acc_822D4200(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0xFFFFFFFFu;
    *(unsigned char*)((char*)a0 + 264) = (unsigned char)0x0u;
}
void Acc_822D4260(char* a0)
{
    *(unsigned char*)((char*)a0 + 264) = (unsigned char)0x1u;
}
void Acc_822D90A0(char* a0)
{
    *(unsigned char*)((char*)a0 + 49) = (unsigned char)0x0u;
}
unsigned int Acc_823054D4(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_82306978(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
void Acc_8230B4C8(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
}
void Acc_82311580(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
}
void Acc_823117A0(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
}
void Acc_82326D60(char* a0)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x1u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)0x0u;
}
void Acc_82329560(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 84) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 92) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 96) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 100) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 124) = (unsigned int)0x0u;
}
unsigned int Acc_82344774(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
void Acc_823498B8(char* a0, unsigned int a1, unsigned int a2, unsigned int a3)
{
    *(unsigned int*)((char*)a0 + 1352) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 1344) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 1348) = (unsigned int)a3;
}
void Acc_8234F3D0(char* a0)
{
    *(unsigned int*)((char*)a0 + 1376) = (unsigned int)((*(unsigned int*)((char*)a0 + 1376)) | 0x1u);
}
void Acc_8234F648(char* a0)
{
    *(unsigned int*)((char*)a0 + 1376) = (unsigned int)((*(unsigned int*)((char*)a0 + 1376)) | 0x1000u);
}
void Acc_823582F8(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(a0 + 0x8u);
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
}
unsigned int Acc_82358318(char* a0)
{
    return (unsigned int)((((*(unsigned int*)((char*)a0 + 4)) + 0x3u) >> 0x2u) + 0x2u);
}
unsigned int Acc_8236D850(char* a0, unsigned int a1, unsigned int a2)
{
    return (unsigned int)((a2 << (*(unsigned int*)((char*)a0 + 240))) | ((*(unsigned int*)((char*)a0 + 232)) & a1));
}
unsigned int Acc_8236D868(char* a0, unsigned int a1)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 232)) & a1);
}
unsigned int Acc_8236D878(char* a0, unsigned int a1)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 236)) & a1) >> (*(unsigned int*)((char*)a0 + 240)));
}
unsigned int Acc_823769BC(unsigned int a0, int unused1, int unused2, int unused3, int unused4, int unused5, int unused6, unsigned int a7)
{
    return (unsigned int)((a0 & 0xF0FFFFFFu) | a7);
}
void Acc_823A1E00(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
}
unsigned int Acc_823D89D0(char* a0, int unused1, int unused2, unsigned int a3)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 44)) - a3);
}
void Acc_823F19E8(char* a0, int unused1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(a2 + (*(unsigned int*)((char*)a0 + 16)));
}
void Acc_823F1DB0(char* a0)
{
    *(unsigned int*)((char*)a0 + 124) = (unsigned int)0x1u;
}
unsigned int Acc_823F4A98(char* a0)
{
    *(unsigned int*)((char*)a0 + 136) = (unsigned int)((*(unsigned int*)((char*)a0 + 136)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 136)) + 0x1u);
}
void Acc_823F4AB0(char* a0, unsigned int a1)
{
    *(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 128)) + 272) = (unsigned int)a1;
    *(unsigned short*)((char*)a0 + 156) = (unsigned short)((*(unsigned short*)((char*)a0 + 156)) + 0x1u);
}
unsigned int Acc_823FB7A0(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE4CC(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE4D8(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE9DC(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
