#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_82266DE8(char* a0, char* a1)
{
    float t0 = (*(float*)((char*)a1 + 8));
    float t1 = (*(float*)((char*)a1 + 4));
    float t2 = (*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 64) = (float)t2;
    *(float*)((char*)a0 + 68) = (float)t1;
    *(float*)((char*)a0 + 72) = (float)t0;
}
void Acc_8226C600(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 48));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 52));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 56));
}
void Acc_8226C620(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 32));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 36));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 56)) + 40));
}
void Acc_8226E6A0(char* a0, char* a1)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 56));
    unsigned int t1 = (*(unsigned int*)((char*)t0 + 48));
    unsigned int t2 = (*(unsigned int*)((char*)t0 + 52));
    unsigned int t3 = (*(unsigned int*)((char*)t0 + 56));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t1;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t2;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)t3;
}
void Acc_822701D0(unsigned int a0, unsigned int a1)
{
    *(unsigned char*)((char*)(a1 + a0) + 57) = (unsigned char)0x1u;
}
void Acc_822701E0(unsigned int a0, unsigned int a1)
{
    *(unsigned char*)((char*)(a1 + a0) + 57) = (unsigned char)0x0u;
}
unsigned int Acc_822D0DB0(char* a0, unsigned int a1)
{
    return (unsigned int)((a1 - ((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 76)) + 80)) + 0xFFFFFFFFu)) == 0x0u);
}
void Acc_822D1EB0(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
}
void Acc_822D1ED8(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0xFFFFFFFFu;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0xFFFFFFFFu;
}
void Acc_822D40D0(char* a0)
{
    unsigned int t0 = (*(unsigned int*)((char*)a0 + 64));
    unsigned int t1 = (*(unsigned int*)((char*)t0 + 32));
    *(unsigned int*)((char*)a0 + 80) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 84) = (unsigned char)0x1u;
    *(unsigned char*)((char*)a0 + 76) = (unsigned char)(t1 & 0x1u);
}
unsigned int Acc_823054D4(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_82306978(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_82344774(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823F4A98(char* a0)
{
    *(unsigned int*)((char*)a0 + 136) = (unsigned int)((*(unsigned int*)((char*)a0 + 136)) + 0x1u);
    return (unsigned int)((*(unsigned int*)((char*)a0 + 136)) + 0x1u);
}
unsigned int Acc_823FB7A0(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE4CC(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE4D8(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FE9DC(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FEF00(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_823FF060(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
unsigned int Acc_824193D8(int unused0, int unused1, int unused2, int unused3, int unused4, unsigned int a5)
{
    return (unsigned int)0x1u;
}
void Acc_824989D8(char* a0)
{
    unsigned int t0 = (*(unsigned int*)((char*)a0 + 0));
    unsigned int t1 = (*(unsigned int*)((char*)a0 + 4));
    unsigned int t2 = (*(unsigned int*)((char*)(t0 + 0x3CCu) + 4));
    *(unsigned int*)((char*)t1 + 0) = (unsigned int)t2;
    *(unsigned int*)((char*)(t0 + 0x3CCu) + 4) = (unsigned int)t1;
}
unsigned int Acc_82510000(char* a0)
{
    return (unsigned int)(((a0 + 0xCu) - (*(unsigned int*)((char*)a0 + 8))) == 0x0u);
}
unsigned int Acc_8253AF28(char* a0, unsigned int a1)
{
    *(unsigned char*)((char*)a0 + 562) = (unsigned char)a1;
    return (unsigned int)0x0u;
}
void Acc_8258EC58(int unused0, char* a1, char* a2)
{
    *(unsigned int*)((char*)a2 + 56) = (unsigned int)a1;
    *(unsigned int*)((char*)a2 + 44) = (unsigned int)(*(unsigned int*)((char*)a1 + 44));
    *(unsigned int*)((char*)a1 + 44) = (unsigned int)a2;
    *(unsigned int*)((char*)a1 + 24) = (unsigned int)((*(unsigned int*)((char*)a1 + 24)) | 0x10u);
}
unsigned int Acc_825C6320(char* a0)
{
    return (unsigned int)((((0x1u << (*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 168)) + 28))) + 0xFFFFFFFFu) - (*(unsigned int*)((char*)a0 + 104))) == 0x0u);
}
void Acc_825E5140(char* a0, char* a1)
{
    unsigned char t0 = (*(unsigned char*)((char*)a1 + 20));
    unsigned char t1 = (*(unsigned char*)((char*)a1 + 21));
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)t0;
    *(unsigned char*)((char*)a0 + 1) = (unsigned char)t1;
}
void Acc_825E7658(char* a0, char* a1)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 28));
    unsigned int t1 = (*(unsigned int*)((char*)a1 + 32));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t0;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t1;
}
void Acc_825FC0F8(char* a0)
{
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(a0 + 0x10u);
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(((*(unsigned int*)((char*)a0 + 0)) << 0x4u) + (a0 + 0x10u));
}
unsigned int Acc_8260C880(char* a0, char* a1)
{
    *(unsigned int*)((char*)a1 + 0) = (unsigned int)0x1u;
    return (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 20)) + 20));
}
void Acc_8261A700(char* a0, char* a1, char* a2)
{
    *(float*)((char*)a1 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 4));
    *(float*)((char*)a1 + 4) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 8));
    *(float*)((char*)a1 + 8) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 12));
    *(float*)((char*)a2 + 0) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 16));
    *(float*)((char*)a2 + 4) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 20));
    *(float*)((char*)a2 + 8) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 24)) + 24));
}
void Acc_82649F98(char* a0, unsigned int a1, unsigned int a2, char* a3)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a2;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)(*(unsigned int*)((char*)a3 + 12));
}
void Acc_8264B488(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(a0 + 0x4u);
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)(a0 + 0x4u);
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(a0 + 0xCu);
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(a0 + 0xCu);
    *(unsigned char*)((char*)a0 + 20) = (unsigned char)0x1u;
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 40) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 44) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 48) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x0u;
}
unsigned int Acc_826C0F08(char* a0, unsigned int a1)
{
    return (unsigned int)(((a1 + (a1 << 0x2u)) << 0x2u) + (*(unsigned int*)((char*)a0 + 16)));
}
void Acc_826D1DB8(char* a0)
{
    *(float*)((char*)a0 + 16) = (float)(*(float*)((char*)a0 + 4));
    *(float*)((char*)a0 + 4) = (float)(*(float*)((char*)a0 + 16));
    *(float*)((char*)a0 + 32) = (float)(*(float*)((char*)a0 + 8));
    *(float*)((char*)a0 + 8) = (float)(*(float*)((char*)a0 + 32));
    *(float*)((char*)a0 + 36) = (float)(*(float*)((char*)a0 + 24));
    *(float*)((char*)a0 + 24) = (float)(*(float*)((char*)a0 + 36));
}
void Acc_827007D0(char* a0, char* a1)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 20));
    unsigned int t1 = (*(unsigned int*)((char*)a1 + 24));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t0;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t1;
}
void Acc_827008C8(char* a0, char* a1)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 12));
    unsigned int t1 = (*(unsigned int*)((char*)a1 + 16));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t0;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t1;
}
void Acc_82700980(char* a0, char* a1)
{
    unsigned int t0 = (*(unsigned int*)((char*)a1 + 16));
    unsigned int t1 = (*(unsigned int*)((char*)a1 + 20));
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)t0;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)t1;
}
unsigned int Acc_82708780(int unused0, char* a1)
{
    return (unsigned int)(((((((((((*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 44)) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 40))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 36))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 32))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 28))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 24))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 20))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 16))) ^ (*(unsigned int*)((char*)a1 + 16))) >> 0x7u) ^ (((((((((*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 44)) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 40))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 36))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 32))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 28))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 24))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 20))) ^ (*(unsigned int*)((char*)(*(unsigned int*)((char*)a1 + 20)) + 16))) ^ (*(unsigned int*)((char*)a1 + 16))));
}
void Acc_82754888(char* a0)
{
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)((*(unsigned int*)((char*)a0 + 24)) + 0xFFFFFFFFu);
}
