#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_821A47E0(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 4)) + 8)) + 0xFFFFFFFFu);
}
void Acc_821A47F8(char* a0)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)((*(unsigned int*)((char*)a0 + 8)) + 0xFFFFFFFFu);
}
unsigned int Acc_821A4820(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 8)) >> 0x1Fu);
}
void Acc_821A4AA0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 20) = (unsigned char)(*(unsigned char*)((char*)a1 + 20));
}
void Acc_821A4D50(char* a0, char* a1)
{
    *(unsigned short*)((char*)a0 + 16) = (unsigned short)(*(unsigned char*)((char*)a1 + 8));
    *(unsigned short*)((char*)a0 + 18) = (unsigned short)(*(unsigned char*)((char*)a1 + 9));
}
void Acc_821A4D80(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_821A4E20(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned char*)((char*)a1 + 8));
}
void Acc_821A5BF0(char* a0)
{
    *(unsigned char*)((char*)a0 + 80) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 81) = (unsigned char)0x0u;
}
void Acc_821A5C48(char* a0)
{
    *(unsigned char*)((char*)a0 + 24) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 25) = (unsigned char)0x1u;
    *(unsigned int*)((char*)a0 + 52) = (unsigned int)(*(unsigned int*)((char*)a0 + 28));
    *(unsigned int*)((char*)a0 + 56) = (unsigned int)(*(unsigned int*)((char*)a0 + 32));
    *(unsigned int*)((char*)a0 + 60) = (unsigned int)(*(unsigned int*)((char*)a0 + 36));
}
void Acc_821A5C78(char* a0, int unused1, unsigned int a2, float f0)
{
    *(float*)((char*)a0 + 0) = (float)f0;
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)a2;
}
void Acc_821A5C88(char* a0, char* a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)a2;
}
void Acc_821A62C8(char* a0, unsigned int a1, float f0, float f1)
{
    *(float*)((char*)a0 + 344) = (float)f0;
    *(float*)((char*)a0 + 348) = (float)f1;
    *(unsigned int*)((char*)a0 + 328) = (unsigned int)a1;
    *(unsigned char*)((char*)a0 + 352) = (unsigned char)0x1u;
}
void Acc_821A69D0(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 0) = (unsigned int)0x1u;
}
void Acc_821A7278(char* a0)
{
    *(unsigned int*)((char*)a0 + 88) = (unsigned int)0x0u;
}
void Acc_821A7BE8(int unused0, char* a1, float f0)
{
    *(float*)((char*)a1 + 28) = (float)f0;
    *(unsigned char*)((char*)a1 + 2) = (unsigned char)0x1u;
}
unsigned int Acc_821A8CC8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 64)) + 16)) == 0x1u);
}
void Acc_821AAB20(char* a0)
{
    *(unsigned int*)((char*)a0 + 1984) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 1988) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 1992) = (unsigned int)0x0u;
}
void Acc_821AAE28(char* a0, char* a1, int unused2, unsigned int a3, float f0)
{
    *(unsigned char*)((char*)a0 + 1816) = (unsigned char)0x1u;
    *(float*)((char*)a0 + 1820) = (float)(*(float*)((char*)a1 + 0));
    *(float*)((char*)a0 + 1824) = (float)(*(float*)((char*)a1 + 4));
    *(float*)((char*)a0 + 1828) = (float)(*(float*)((char*)a1 + 8));
    *(unsigned char*)((char*)a0 + 1817) = (unsigned char)a3;
    *(float*)((char*)a0 + 1832) = (float)f0;
}
unsigned int Acc_821AAE58(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 1484)) == 0x0u);
}
unsigned int Acc_821AAE90(unsigned int a0, unsigned int a1)
{
    return (unsigned int)((((a1 + (a1 << 0x1u)) << 0x2u) + a0) + 0x778u);
}
void Acc_821ABB10(char* a0)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)0x4u;
}
void Acc_821ABB20(char* a0, unsigned int a1, unsigned int a2)
{
    *(unsigned int*)((char*)a0 + 36) = (unsigned int)a1;
    *(unsigned int*)((char*)a0 + 32) = (unsigned int)a2;
}
unsigned int Acc_821ABD70(char* a0)
{
    return (unsigned int)(*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 536));
}
unsigned int Acc_821ABD80(char* a0)
{
    return (unsigned int)((*(unsigned char*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 536)) == 0x0u);
}
void Acc_821AC338(char* a0)
{
    *(unsigned char*)((char*)a0 + 25) = (unsigned char)0x1u;
}
void Acc_821AD570(char* a0)
{
    *(unsigned char*)((char*)a0 + 0) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 4) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 8) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 16) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 20) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
}
void Acc_821AD6D8(char* a0)
{
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)0x0u;
}
void Acc_821AE948(char* a0)
{
    *(unsigned int*)((char*)a0 + 12) = (unsigned int)0x0u;
    *(unsigned char*)((char*)a0 + 4) = (unsigned char)0x0u;
}
void Acc_821AE988(char* a0)
{
    *(unsigned int*)((char*)a0 + 28) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 24) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 240) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 236) = (unsigned int)0x0u;
    *(unsigned int*)((char*)a0 + 448) = (unsigned int)(a0 + 0x18u);
    *(unsigned int*)((char*)a0 + 452) = (unsigned int)(a0 + 0xECu);
}
void Acc_821AED50(char* a0, int unused1, char* a2)
{
    *(unsigned int*)((char*)a2 + 0) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 48));
    *(unsigned int*)((char*)a2 + 4) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 52));
    *(unsigned int*)((char*)a2 + 8) = (unsigned int)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 56));
}
void Acc_821B47F8(char* a0)
{
    *(float*)((char*)a0 + 16) = (float)(*(float*)((char*)(*(unsigned int*)((char*)(*(unsigned int*)((char*)a0 + 8)) + 56)) + 52));
}
unsigned int Acc_821BC3B8(char* a0)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 12)) == 0x0u);
}
void Acc_821BDDA0(char* a0)
{
    *(unsigned char*)((char*)a0 + 16) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 588) = (unsigned char)0x0u;
    *(unsigned char*)((char*)a0 + 589) = (unsigned char)0x0u;
    *(unsigned int*)((char*)a0 + 344) = (unsigned int)0x0u;
}
unsigned int Acc_821C1D40(char* a0, unsigned int a1)
{
    return (unsigned int)((*(unsigned int*)((char*)a0 + 140)) + (a1 << 0x6u));
}
unsigned int Acc_821C2C18(char* a0)
{
    return (unsigned int)(((*(unsigned int*)((char*)a0 + 468)) >> 0x6u) & 0x1u);
}
void Acc_821C2C28(char* a0)
{
    *(float*)((char*)a0 + 1040) = (float)(*(float*)((char*)(*(unsigned int*)((char*)a0 + 56)) + 52));
}
void Acc_821C8930(char* a0, float f0)
{
    *(float*)((char*)a0 + 84) = (float)f0;
}
void Acc_821C8938(char* a0, float f0)
{
    *(float*)((char*)a0 + 88) = (float)f0;
}
void Acc_821C8940(char* a0, char* a1)
{
    *(unsigned int*)((char*)a0 + 68) = (unsigned int)(*(unsigned int*)((char*)a1 + 0));
    *(unsigned int*)((char*)a0 + 72) = (unsigned int)(*(unsigned int*)((char*)a1 + 4));
    *(unsigned int*)((char*)a0 + 76) = (unsigned int)(*(unsigned int*)((char*)a1 + 8));
}
void Acc_821C8960(char* a0, float f0, float f1, float f2)
{
    *(float*)((char*)a0 + 68) = (float)f0;
    *(float*)((char*)a0 + 72) = (float)f1;
    *(float*)((char*)a0 + 76) = (float)f2;
}
