#include "types.h"

// Single-expression accessors, 40 of them in this file.
//
// Generated by tools/gen_accessors.py from each function's own encoding --
// a getter, a setter, a pointer adjust or an empty body, each one
// expression long. Every one was compiled and compared against the retail
// bytes before its manifest row was written; nothing here is asserted.
//
// The value is the FIELD OFFSETS. `lwz r3,0x24(r3)` says its class has a
// 4-byte field at 0x24, and tools/vtables.py can say which class, because
// it knows which vtable the function sits in.
//
// Do not hand-edit: regenerate.

struct VObj;
typedef void (*VFn)(VObj*);
struct VTbl { VFn slot[256]; };
struct VObj { VTbl* vt; };

void Acc_826C1258(void* p, u32 v) { *(u32*)((char*)p + 8) = v; }
void Acc_826C3D80() { }
void Acc_826C3D88() { }
void Acc_826C3D90() { }
void Acc_826C3D98() { }
void Acc_826C3DA0() { }
void Acc_826C3DA8() { }
void Acc_826C3DB0() { }
void Acc_826C3DB8() { }
void Acc_826C3DC0() { }
void Acc_826C3DC8() { }
void Acc_826C3DD0() { }
void Acc_826C58C8() { }
void Acc_826C58D0() { }
void Acc_826C58D8() { }
void Acc_826C8718() { }
void Acc_826C8720() { }
u32 Acc_826D4440(void* p) { return *(u32*)((char*)p + 12); }
u32 Acc_826D4448(void* p) { return *(u32*)((char*)p + 12); }
float Acc_826D46B8(void* p) { return *(float*)((char*)p + 216); }
float Acc_826D4F58(void* p) { return *(float*)((char*)p + 68); }
u32 Acc_826D8E30(void* p) { return *(u32*)((char*)p + 520); }
void Acc_826DD3F0() { }
void Acc_826DD430() { }
void Acc_826E38F8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 0);
    q->vt->slot[4](q);
}
void Acc_826E4008(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[18](q);
}
void Acc_826E4118(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[1](q);
}
void Acc_826E4130(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[3](q);
}
void Acc_826E4148(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[4](q);
}
void Acc_826E4160(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[5](q);
}
void Acc_826E4178(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[6](q);
}
void Acc_826E4190(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[7](q);
}
void Acc_826E41A8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[9](q);
}
void Acc_826E41C0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[10](q);
}
void Acc_826E41D8(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[11](q);
}
void Acc_826E41F0(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[12](q);
}
void Acc_826E4208(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[13](q);
}
void Acc_826E4220(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[14](q);
}
void Acc_826E4238(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[16](q);
}
void Acc_826E4250(void* p)
{
    VObj* q = *(VObj**)((char*)p + 16);
    q->vt->slot[17](q);
}
