#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each function's entire body materialises one constant into r3 and returns.
// 345 functions in the image do this, in two encodings: 194 as
//     lis r3,hi ; ori r3,r3,lo ; blr        any 32-bit constant
// and 151 as
//     li  r3,imm ; blr                      constant in [-32768, 32767]
// All 345 target r3, so all 345 are returns rather than some other use of a
// materialised constant.
//
// They are virtual-only: of the 12-byte form 192 of 194 appear in a vtable
// and 2 of 194 are reached by a direct bl; of the 8-byte form 140 of 151
// appear in a vtable and 11 of 151 are called directly. So the constant is
// an identity, not a computation. tools/vtables.py classifies the 12-byte
// population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a 0x100-spaced
// enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not identities at
// all.
//
// The game's own code carries no RTTI -- zero of the 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

s32 TypeId_82275F20() { return 33; }
s32 TypeId_82275F28() { return 34; }
s32 TypeId_82275F30() { return 35; }
s32 TypeId_82275F38() { return 36; }
s32 TypeId_82275F40() { return 37; }
s32 TypeId_82275F48() { return 38; }
s32 TypeId_82275F50() { return 39; }
s32 TypeId_82275F58() { return 40; }
s32 TypeId_82275F60() { return 41; }
s32 TypeId_82275F68() { return 42; }
s32 TypeId_82275F70() { return 43; }
s32 TypeId_82291F10() { return 25; }
s32 TypeId_82291F18() { return 24; }
s32 TypeId_822D0E78() { return 0; }
s32 TypeId_822D3E88() { return 98; }
s32 TypeId_822D3E90() { return 177; }
s32 TypeId_823A2EC0() { return 0; }
s32 TypeId_823A2F3C() { return 0; }
s32 TypeId_823A2FD4() { return 0; }
s32 TypeId_8241024C() { return 0; }
s32 TypeId_824B9680() { return 13; }
s32 TypeId_824D0A80() { return 1; }
s32 TypeId_825142F0() { return 2; }
s32 TypeId_8252DD40() { return 76; }
s32 TypeId_8253C730() { return 33; }
s32 TypeId_825406A0() { return 78; }
s32 TypeId_8257F598() { return 75; }
s32 TypeId_82591338() { return 14; }
s32 TypeId_825AD7C8() { return 51; }
s32 TypeId_825CDF6C() { return 0; }
s32 TypeId_825EC7DC() { return 0; }
s32 TypeId_825EC9C8() { return 90; }
