#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each function's entire body materialises one constant into r3 and returns.
// 345 functions in the image do this, in two encodings: 194 as
//     lis r3,hi ; ori r3,r3,lo ; blr        any 32-bit constant
// and 151 as
//     li  r3,imm ; blr                      constant in [-32768, 32767]
// All 345 target r3, so all 345 are returns rather than some other use of a
// materialised constant.
//
// They are virtual-only: of the 12-byte form 192 of 194 appear in a vtable
// and 2 of 194 are reached by a direct bl; of the 8-byte form 140 of 151
// appear in a vtable and 11 of 151 are called directly. So the constant is
// an identity, not a computation. tools/vtables.py classifies the 12-byte
// population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a 0x100-spaced
// enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not identities at
// all.
//
// The game's own code carries no RTTI -- zero of the 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

s32 TypeId_825ECA50() { return 37; }
s32 TypeId_825FCE30() { return -1; }
s32 TypeId_8261AB88() { return 112; }
s32 TypeId_8262FD88() { return 0; }
s32 TypeId_82634938() { return 255; }
s32 TypeId_82636170() { return 1; }
s32 TypeId_826368C0() { return 8; }
s32 TypeId_82636B20() { return 7; }
s32 TypeId_82648C70() { return 240; }
s32 TypeId_82648C78() { return 280; }
s32 TypeId_826491D8() { return 1024; }
s32 TypeId_8266DF88() { return 0; }
s32 TypeId_826730F0() { return 1; }
s32 TypeId_82674508() { return 8; }
s32 TypeId_82674B08() { return 48; }
s32 TypeId_82674B10() { return 2; }
s32 TypeId_8267F3F8() { return 2; }
s32 TypeId_8267FC48() { return 64; }
s32 TypeId_8267FC50() { return 1; }
s32 TypeId_82681768() { return 18; }
s32 TypeId_82682750() { return 96; }
s32 TypeId_82696930() { return 0; }
s32 TypeId_82696FE8() { return -1; }
s32 TypeId_826A4E80() { return 4096; }
s32 TypeId_826CDD90() { return 0; }
s32 TypeId_826CDDA8() { return 11; }
s32 TypeId_826D2DC0() { return 9; }
s32 TypeId_826D3A20() { return 6; }
s32 TypeId_826D3E88() { return 14; }
s32 TypeId_826D4438() { return 13; }
s32 TypeId_826D4760() { return 2; }
s32 TypeId_826D4FE8() { return 0; }
