#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each function's entire body materialises one constant into r3 and returns.
// 345 functions in the image do this, in two encodings: 194 as
//     lis r3,hi ; ori r3,r3,lo ; blr        any 32-bit constant
// and 151 as
//     li  r3,imm ; blr                      constant in [-32768, 32767]
// All 345 target r3, so all 345 are returns rather than some other use of a
// materialised constant.
//
// They are virtual-only: of the 12-byte form 192 of 194 appear in a vtable
// and 2 of 194 are reached by a direct bl; of the 8-byte form 140 of 151
// appear in a vtable and 11 of 151 are called directly. So the constant is
// an identity, not a computation. tools/vtables.py classifies the 12-byte
// population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a 0x100-spaced
// enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not identities at
// all.
//
// The game's own code carries no RTTI -- zero of the 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

s32 TypeId_8219F058() { return 17; }
s32 TypeId_821A4650() { return 3; }
s32 TypeId_821A4F00() { return 179; }
s32 TypeId_821B15C0() { return 14; }
s32 TypeId_821B15C8() { return 8; }
s32 TypeId_821B15D0() { return 11; }
s32 TypeId_821B15D8() { return 12; }
s32 TypeId_821B15E0() { return 15; }
s32 TypeId_821B15E8() { return 16; }
s32 TypeId_821B15F0() { return 10; }
s32 TypeId_821BC3A0() { return 4; }
s32 TypeId_821CA3A0() { return 19; }
s32 TypeId_821CA3A8() { return 5; }
s32 TypeId_821CA3B0() { return 23; }
s32 TypeId_821CA3B8() { return 6; }
s32 TypeId_821CA3C0() { return 7; }
s32 TypeId_821CA3C8() { return 18; }
s32 TypeId_8220C1D8() { return 20; }
s32 TypeId_8221F180() { return 9; }
s32 TypeId_82220FA0() { return 1; }
u32 TypeId_8224EB18() { return 0x7FC00000u; }
s32 TypeId_82274190() { return 45; }
s32 TypeId_82275ED0() { return 44; }
s32 TypeId_82275ED8() { return 21; }
s32 TypeId_82275EE0() { return 22; }
s32 TypeId_82275EE8() { return 26; }
s32 TypeId_82275EF0() { return 27; }
s32 TypeId_82275EF8() { return 28; }
s32 TypeId_82275F00() { return 29; }
s32 TypeId_82275F08() { return 30; }
s32 TypeId_82275F10() { return 31; }
s32 TypeId_82275F18() { return 32; }
