#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each function's entire body materialises one constant into r3 and returns.
// 345 functions in the image do this, in two encodings: 194 as
//     lis r3,hi ; ori r3,r3,lo ; blr        any 32-bit constant
// and 151 as
//     li  r3,imm ; blr                      constant in [-32768, 32767]
// All 345 target r3, so all 345 are returns rather than some other use of a
// materialised constant.
//
// They are virtual-only: of the 12-byte form 192 of 194 appear in a vtable
// and 2 of 194 are reached by a direct bl; of the 8-byte form 140 of 151
// appear in a vtable and 11 of 151 are called directly. So the constant is
// an identity, not a computation. tools/vtables.py classifies the 12-byte
// population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a 0x100-spaced
// enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not identities at
// all.
//
// The game's own code carries no RTTI -- zero of the 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

s32 TypeId_826D7750() { return 3; }
s32 TypeId_826D7850() { return 12; }
s32 TypeId_826E4310() { return 4097; }
s32 TypeId_826FCC88() { return 12; }
s32 TypeId_826FFD68() { return 0; }
s32 TypeId_826FFD70() { return 0; }
s32 TypeId_82709C80() { return 768; }
s32 TypeId_82712EA0() { return 1; }
s32 TypeId_82715138() { return 23; }
s32 TypeId_8271B078() { return 4; }
s32 TypeId_8271F2E8() { return 6; }
s32 TypeId_8271FB08() { return 13; }
s32 TypeId_8272C570() { return 1; }
s32 TypeId_8272C578() { return -1; }
s32 TypeId_82790EC8() { return 512; }
s32 TypeId_82790F98() { return 0; }
s32 TypeId_8279D4A0() { return 0; }
s32 TypeId_8279E708() { return 1; }
s32 TypeId_8279E710() { return 0; }
s32 TypeId_827AE9D0() { return 3; }
s32 TypeId_827AF3A0() { return 15; }
s32 TypeId_827AF690() { return 18; }
s32 TypeId_827AFD28() { return 19; }
s32 TypeId_827ED5B0() { return -1; }
s32 TypeId_827F8158() { return 11; }
s32 TypeId_827FE040() { return 2; }
s32 TypeId_82815348() { return 36; }
s32 TypeId_828177C0() { return 30; }
s32 TypeId_8281ACB0() { return 17; }
s32 TypeId_8281C258() { return 26; }
s32 TypeId_8281E2F8() { return 7; }
s32 TypeId_82846160() { return 1; }
