#include "types.h"

// Constant-returning virtuals, 24 of them in this file.
//
// Each function's entire body materialises one constant into r3 and returns.
// 345 functions in the image do this, in two encodings: 194 as
//     lis r3,hi ; ori r3,r3,lo ; blr        any 32-bit constant
// and 151 as
//     li  r3,imm ; blr                      constant in [-32768, 32767]
// All 345 target r3, so all 345 are returns rather than some other use of a
// materialised constant.
//
// They are virtual-only: of the 12-byte form 192 of 194 appear in a vtable
// and 2 of 194 are reached by a direct bl; of the 8-byte form 140 of 151
// appear in a vtable and 11 of 151 are called directly. So the constant is
// an identity, not a computation. tools/vtables.py classifies the 12-byte
// population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a 0x100-spaced
// enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not identities at
// all.
//
// The game's own code carries no RTTI -- zero of the 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

s32 TypeId_82846168() { return 1; }
s32 TypeId_82846170() { return 1; }
s32 TypeId_82846178() { return -1; }
s32 TypeId_828461B8() { return 0; }
s32 TypeId_828463A0() { return 1; }
s32 TypeId_8286BED0() { return 9; }
s32 TypeId_8286E140() { return 8; }
s32 TypeId_8286FB48() { return 10; }
s32 TypeId_828709D8() { return 21; }
s32 TypeId_82872730() { return 25; }
s32 TypeId_82873EC8() { return 27; }
s32 TypeId_82875518() { return 24; }
s32 TypeId_8287A170() { return 41; }
s32 TypeId_8287D108() { return 35; }
s32 TypeId_8287F8A8() { return 42; }
s32 TypeId_828823B8() { return 20; }
s32 TypeId_82884868() { return 15; }
s32 TypeId_82885B80() { return 16; }
s32 TypeId_82887878() { return 18; }
s32 TypeId_8288AE30() { return 38; }
s32 TypeId_8288C618() { return 39; }
s32 TypeId_8288D978() { return 40; }
s32 TypeId_8288EF88() { return 22; }
s32 TypeId_828DE490() { return 256; }
