#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_821AE768() { return 0x725C0C42u; }
u32 TypeId_821AE778() { return 0xFA2D2570u; }
u32 TypeId_821AE788() { return 0x3E0941ADu; }
u32 TypeId_821AE798() { return 0xDC3A1307u; }
u32 TypeId_821AE7A8() { return 0x7FD6A393u; }
u32 TypeId_821AE7B8() { return 0xCC3A4DFEu; }
u32 TypeId_821AE7C8() { return 0xA1CEE0D3u; }
u32 TypeId_821AE7D8() { return 0x5CA86C4Cu; }
u32 TypeId_821AE7E8() { return 0x55875237u; }
u32 TypeId_821AE7F8() { return 0x7838E47Cu; }
u32 TypeId_821AE808() { return 0xF0A20B00u; }
u32 TypeId_821AE818() { return 0x6F6FDA6Bu; }
u32 TypeId_821AE828() { return 0x634DA9A4u; }
u32 TypeId_821AE838() { return 0x9DB83D10u; }
u32 TypeId_821AE848() { return 0x4766616Fu; }
u32 TypeId_821AE858() { return 0x2A17999Bu; }
u32 TypeId_821AE868() { return 0xCF8433D5u; }
u32 TypeId_821AE878() { return 0x3F7C56C9u; }
u32 TypeId_821AE888() { return 0x1F36793Bu; }
u32 TypeId_821AE898() { return 0x10D63B7Au; }
u32 TypeId_821AE8A8() { return 0x4B135530u; }
u32 TypeId_821AE8B8() { return 0xDA789044u; }
u32 TypeId_821AE8C8() { return 0x54497409u; }
u32 TypeId_821AE8D8() { return 0x9950E449u; }
u32 TypeId_821AE8E8() { return 0x23FCD139u; }
u32 TypeId_821AE8F8() { return 0x88671173u; }
u32 TypeId_821AE908() { return 0xCD037DADu; }
u32 TypeId_821AE918() { return 0x3FED91AAu; }
u32 TypeId_821BC390() { return 0xFD239E46u; }
u32 TypeId_821BC3C8() { return 0x12E94D45u; }
u32 TypeId_821BC430() { return 0x928A25FCu; }
u32 TypeId_821BC440() { return 0xBA6835FFu; }
