#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_821C7F70() { return 0x098F1B17u; }
u32 TypeId_821C7F80() { return 0xCF3BD772u; }
u32 TypeId_821C7F90() { return 0xF570755Cu; }
u32 TypeId_821C7FA0() { return 0x8CCE56E2u; }
u32 TypeId_821C7FB0() { return 0x0B8B3028u; }
u32 TypeId_821C7FC0() { return 0xE61F36DEu; }
u32 TypeId_821D1CA8() { return 0xF7756BA5u; }
u32 TypeId_821D34F0() { return 0x89176D7Du; }
u32 TypeId_821D9A10() { return 0xEE05B233u; }
u32 TypeId_821D9A20() { return 0x33986A11u; }
u32 TypeId_821D9A38() { return 0x55910AB7u; }
u32 TypeId_821D9A48() { return 0x9511909Du; }
u32 TypeId_821D9A58() { return 0xD9EFDBC9u; }
u32 TypeId_821D9A68() { return 0xC686B2E1u; }
u32 TypeId_821D9AE0() { return 0xE6C57417u; }
u32 TypeId_821D9AF0() { return 0x90416D1Cu; }
u32 TypeId_8232EE58() { return 0x80004001u; }
u32 TypeId_823D8BB8() { return 0x000F4240u; }
u32 TypeId_825E4670() { return 0x736E6373u; }
u32 TypeId_825E4680() { return 0x736D6874u; }
u32 TypeId_825E4690() { return 0x736E6C74u; }
u32 TypeId_825E46A0() { return 0x736D6773u; }
u32 TypeId_825E46B0() { return 0x736B6E6Cu; }
u32 TypeId_825E59A8() { return 0x73657563u; }
u32 TypeId_825E7670() { return 0x736D7270u; }
u32 TypeId_82707DC8() { return 0x00008000u; }
u32 TypeId_82709618() { return 0x00008500u; }
u32 TypeId_82713B20() { return 0x00008300u; }
u32 TypeId_8271B080() { return 0x627DAFCFu; }
u32 TypeId_827F86C0() { return 0x00008400u; }
u32 TypeId_828493C0() { return 0x00008200u; }
u32 TypeId_8284DA38() { return 0xEFFFAFCFu; }
