#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_821AE260() { return 0xD3DBCD1Du; }
u32 TypeId_821AE270() { return 0x4AA40A6Eu; }
u32 TypeId_821AE280() { return 0x1B9BE8ADu; }
u32 TypeId_821AE290() { return 0x847342C3u; }
u32 TypeId_821AE2A0() { return 0xB4B6E161u; }
u32 TypeId_821AE2B0() { return 0x1D8E3B77u; }
u32 TypeId_821AE2C0() { return 0x457818A1u; }
u32 TypeId_821AE2D0() { return 0x2F5C488Cu; }
u32 TypeId_821AE2E0() { return 0x5272A24Bu; }
u32 TypeId_821AE2F0() { return 0xBBFADCF3u; }
u32 TypeId_821AE300() { return 0x622DF635u; }
u32 TypeId_821AE310() { return 0x6D7B2193u; }
u32 TypeId_821AE320() { return 0xE7F37266u; }
u32 TypeId_821AE330() { return 0x003D16CDu; }
u32 TypeId_821AE3C8() { return 0xDF79BEFDu; }
u32 TypeId_821AE460() { return 0x96D1A1FDu; }
u32 TypeId_821AE4F8() { return 0x14AE9360u; }
u32 TypeId_821AE508() { return 0x1C5B3812u; }
u32 TypeId_821AE518() { return 0x2BA8AFD4u; }
u32 TypeId_821AE528() { return 0x95BC4F25u; }
u32 TypeId_821AE538() { return 0x26DFF12Bu; }
u32 TypeId_821AE5D0() { return 0x2A5BD78Du; }
u32 TypeId_821AE5E0() { return 0xD1DD8099u; }
u32 TypeId_821AE5F0() { return 0x698F47B8u; }
u32 TypeId_821AE600() { return 0x5DAFAAC1u; }
u32 TypeId_821AE610() { return 0x2840596Cu; }
u32 TypeId_821AE620() { return 0xEDF31EB4u; }
u32 TypeId_821AE630() { return 0x0387DC96u; }
u32 TypeId_821AE640() { return 0x3E831EEDu; }
u32 TypeId_821AE650() { return 0x3CF0C7FEu; }
u32 TypeId_821AE6C0() { return 0x96D19EEDu; }
u32 TypeId_821AE758() { return 0xA5B7D8C8u; }
