#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_821C7D70() { return 0x3A58D11Bu; }
u32 TypeId_821C7D80() { return 0x0F158907u; }
u32 TypeId_821C7D90() { return 0xF4BFED0Fu; }
u32 TypeId_821C7DA0() { return 0xDA0CC2F9u; }
u32 TypeId_821C7DB0() { return 0xCFBB434Eu; }
u32 TypeId_821C7DC0() { return 0x1836CF18u; }
u32 TypeId_821C7DD0() { return 0x3A61E1A3u; }
u32 TypeId_821C7DE0() { return 0xFA817831u; }
u32 TypeId_821C7DF0() { return 0x18EE9D20u; }
u32 TypeId_821C7E00() { return 0xFEABFB6Au; }
u32 TypeId_821C7E10() { return 0xFD3BCC1Cu; }
u32 TypeId_821C7E20() { return 0x352422D9u; }
u32 TypeId_821C7E30() { return 0x7C563A4Au; }
u32 TypeId_821C7E40() { return 0xD045A852u; }
u32 TypeId_821C7E50() { return 0x199C5DC2u; }
u32 TypeId_821C7E60() { return 0x7815D244u; }
u32 TypeId_821C7E70() { return 0x5FC62F38u; }
u32 TypeId_821C7E80() { return 0x9C10E73Bu; }
u32 TypeId_821C7E90() { return 0x61A01F7Du; }
u32 TypeId_821C7EA0() { return 0x41426C6Au; }
u32 TypeId_821C7EB0() { return 0xAAD297BCu; }
u32 TypeId_821C7EC0() { return 0xB897522Fu; }
u32 TypeId_821C7ED0() { return 0x456DE2D8u; }
u32 TypeId_821C7EE0() { return 0x9FE9DCB5u; }
u32 TypeId_821C7EF0() { return 0x69DC34BBu; }
u32 TypeId_821C7F00() { return 0xDD16B40Eu; }
u32 TypeId_821C7F10() { return 0xBA739AF9u; }
u32 TypeId_821C7F20() { return 0x72888246u; }
u32 TypeId_821C7F30() { return 0xFC46AB83u; }
u32 TypeId_821C7F40() { return 0x4E88847Eu; }
u32 TypeId_821C7F50() { return 0x3FF49CADu; }
u32 TypeId_821C7F60() { return 0x174B72DAu; }
