#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_82126318() { return 0x80004005u; }
u32 TypeId_821ADEA0() { return 0x83993522u; }
u32 TypeId_821ADEB0() { return 0x82201CCFu; }
u32 TypeId_821ADF78() { return 0x957664BBu; }
u32 TypeId_821ADF88() { return 0x60878ADCu; }
u32 TypeId_821ADF98() { return 0xA91E4975u; }
u32 TypeId_821ADFA8() { return 0xCE65A00Cu; }
u32 TypeId_821ADFB8() { return 0x2EF33CDBu; }
u32 TypeId_821AE050() { return 0xE04735A5u; }
u32 TypeId_821AE060() { return 0x9E397889u; }
u32 TypeId_821AE100() { return 0x22E53567u; }
u32 TypeId_821AE110() { return 0x96CE7A88u; }
u32 TypeId_821AE120() { return 0x95556235u; }
u32 TypeId_821AE130() { return 0x429D6C58u; }
u32 TypeId_821AE140() { return 0x7863C327u; }
u32 TypeId_821AE150() { return 0x4A506C9Du; }
u32 TypeId_821AE160() { return 0xDED3AF67u; }
u32 TypeId_821AE170() { return 0x153E2F18u; }
u32 TypeId_821AE180() { return 0x4A91ECAEu; }
u32 TypeId_821AE190() { return 0xC4F700D8u; }
u32 TypeId_821AE1A0() { return 0xAFE1279Cu; }
u32 TypeId_821AE1B0() { return 0xA84C3D3Au; }
u32 TypeId_821AE1C0() { return 0xA33E487Bu; }
u32 TypeId_821AE1D0() { return 0xF05CA191u; }
u32 TypeId_821AE1E0() { return 0x129E8F7Du; }
u32 TypeId_821AE1F0() { return 0x4E2D3614u; }
u32 TypeId_821AE200() { return 0x23FC0BC6u; }
u32 TypeId_821AE210() { return 0x0109BB57u; }
u32 TypeId_821AE220() { return 0x9F954932u; }
u32 TypeId_821AE230() { return 0x75A4F8D7u; }
u32 TypeId_821AE240() { return 0x46B1E1A5u; }
u32 TypeId_821AE250() { return 0xBD13F938u; }
