#include "types.h"

// Constant-returning virtuals, 32 of them in this file.
//
// Each is one of the 194 functions in the image whose entire body is
//     lis r3,hi ; ori r3,r3,lo ; blr
// a virtual that returns a 32-bit constant and ignores `this`. 192 of the
// 194 appear in a vtable and only 2 are reached by a direct bl, so the
// constant is an identity, not a computation. tools/vtables.py classifies
// the population: 175 hash-shaped class IDs, 11 FourCC tags, 6 on a
// 0x100-spaced enum, and 2 COM HRESULTs (E_FAIL, E_NOTIMPL) that are not
// identities at all.
//
// The game's own code carries no RTTI -- zero of these 194 are RTTI-named,
// against 1,297 functions that are, all of them Havok's -- so this is the
// engine's own type system, and each constant names one class.
//
// Generated by tools/gen_typeids.py. Do not hand-edit: regenerate.

u32 TypeId_821BD918() { return 0x2EF3935Cu; }
u32 TypeId_821C7880() { return 0xD0762FE1u; }
u32 TypeId_821C7890() { return 0xC65A85F5u; }
u32 TypeId_821C78A0() { return 0xFC57E1DAu; }
u32 TypeId_821C78B0() { return 0x307680C0u; }
u32 TypeId_821C78C0() { return 0xD57AD404u; }
u32 TypeId_821C78D0() { return 0xB80413D6u; }
u32 TypeId_821C78E0() { return 0xBE5CF04Fu; }
u32 TypeId_821C78F0() { return 0xD91878D8u; }
u32 TypeId_821C7900() { return 0x9D1EA338u; }
u32 TypeId_821C7910() { return 0x4EC7C3F6u; }
u32 TypeId_821C7998() { return 0x959D267Du; }
u32 TypeId_821C7AB0() { return 0x3DE3F5BCu; }
u32 TypeId_821C7AC0() { return 0xEF418FCAu; }
u32 TypeId_821C7BB0() { return 0xFF2A858Au; }
u32 TypeId_821C7C60() { return 0xAFFF3262u; }
u32 TypeId_821C7C70() { return 0xDAF925F4u; }
u32 TypeId_821C7C80() { return 0xB2BE860Bu; }
u32 TypeId_821C7C90() { return 0x75BF4415u; }
u32 TypeId_821C7CA0() { return 0x0E9F347Cu; }
u32 TypeId_821C7CB0() { return 0x9312DBFCu; }
u32 TypeId_821C7CC0() { return 0x9428F5DAu; }
u32 TypeId_821C7CD0() { return 0x59010875u; }
u32 TypeId_821C7CE0() { return 0xDA75C0E2u; }
u32 TypeId_821C7CF0() { return 0x06D347B0u; }
u32 TypeId_821C7D00() { return 0xAD08633Cu; }
u32 TypeId_821C7D10() { return 0xDBC285E2u; }
u32 TypeId_821C7D20() { return 0xE3FFDDC6u; }
u32 TypeId_821C7D30() { return 0xCB47802Cu; }
u32 TypeId_821C7D40() { return 0x6BCBFC65u; }
u32 TypeId_821C7D50() { return 0x5936688Cu; }
u32 TypeId_821C7D60() { return 0x0E4569BEu; }
